# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Andi Chandler <andi@gowling.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-09 06:05+0000\n"
"PO-Revision-Date: 2014-09-06 09:06+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: English (United Kingdom) (http://www.transifex.com/projects/p/"
"glance/language/en_GB/)\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: glance/scrubber.py:199
#, python-format
msgid "Failed to find image to delete: %s"
msgstr "Failed to find image to delete: %s"

#: glance/scrubber.py:542
#, python-format
msgid "Unable to delete URI from image %s."
msgstr ""

#: glance/api/common.py:116
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr "Invalid value for option user_storage_quota: %(users_quota)s"

#: glance/api/v2/images.py:828
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""
"Could not find schema properties file %s. Continuing without custom "
"properties"

#: glance/cmd/manage.py:89
msgid ""
"Warning: The db_enforce_mysql_charset option is now deprecated and will be "
"removed in the Juno release. Please migrate DB manually e.g. convert data of "
"all tables to UTF-8 charset."
msgstr ""
"Warning: The db_enforce_mysql_charset option is now deprecated and will be "
"removed in the Juno release. Please migrate DB manually e.g. convert data of "
"all tables to UTF-8 charset."

#: glance/common/store_utils.py:62
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr "Failed to delete image %s in store from URI"

#: glance/common/scripts/image_import/main.py:147
#, python-format
msgid "Task %(task_id)s failed with exception %(error)s"
msgstr ""

#: glance/db/sqlalchemy/api.py:72
msgid "Deadlock detected. Retrying..."
msgstr "Deadlock detected. Retrying..."

#: glance/db/sqlalchemy/api.py:320
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id not in sort_keys; is sort_keys unique?"

#: glance/db/sqlalchemy/metadata.py:218
#, python-format
msgid "Duplicate entry for values: %s"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/namespace.py:89
#, python-format
msgid "Metadata definition namespace not found for id=%s"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/object.py:37
#, python-format
msgid "Metadata definition object not found for id %s"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/property.py:39
#, python-format
msgid "Metadata definition property not found for id=%s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:91
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr "Failed to decrypt location value for image %(image_id)s"

#: glance/image_cache/__init__.py:71
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."

#: glance/image_cache/__init__.py:92
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"

#: glance/image_cache/prefetcher.py:49
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr "Image '%s' is not active. Not caching."

#: glance/image_cache/prefetcher.py:54
#, python-format
msgid "No metadata found for image '%s'"
msgstr "No metadata found for image '%s'"

#: glance/image_cache/prefetcher.py:82
msgid "Failed to successfully cache all images in queue."
msgstr "Failed to successfully cache all images in queue."

#: glance/image_cache/drivers/sqlite.py:458
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr "Failed to delete file %(path)s. Got error: %(e)s"

#: glance/image_cache/drivers/sqlite.py:495
#: glance/image_cache/drivers/xattr.py:446
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr "Cached image file '%s' doesn't exist, unable to delete"

#: glance/openstack/common/network_utils.py:146
msgid "tcp_keepidle not available on your system"
msgstr "tcp_keepidle not available on your system"

#: glance/openstack/common/network_utils.py:153
msgid "tcp_keepintvl not available on your system"
msgstr "tcp_keepintvl not available on your system"

#: glance/openstack/common/network_utils.py:160
msgid "tcp_keepknt not available on your system"
msgstr "tcp_keepknt not available on your system"
