# English (United States) translations for glance.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-04-17 00:01+0000\n"
"PO-Revision-Date: 2013-04-10 10:09+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en_US <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: glance/schema.py:56
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr "custom properties (%(props)s) conflict with base properties"

#: glance/api/authorization.py:90 glance/api/authorization.py:101
#, python-format
msgid "You cannot get image member for %s"
msgstr "You cannot get image member for %s"

#: glance/api/authorization.py:109
#, python-format
msgid "You cannot delete image member for %s"
msgstr "You cannot delete image member for %s"

#: glance/api/authorization.py:118
#, python-format
msgid "You cannot add image member for %s"
msgstr "You cannot add image member for %s"

#: glance/api/authorization.py:128
#, python-format
msgid "You cannot update image member %s"
msgstr "You cannot update image member %s"

#: glance/api/authorization.py:147
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "You are not permitted to create images owned by '%s'."

#: glance/api/authorization.py:165
msgid "You are not permitted to create image members for the image."
msgstr "You are not permitted to create image members for the image."

#: glance/api/authorization.py:170 glance/api/authorization.py:306
msgid "Public images do not have members."
msgstr "Public images do not have members."

#: glance/api/authorization.py:185 glance/api/authorization.py:214
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "You are not permitted to modify '%s' on this image."

#: glance/api/authorization.py:193
msgid "You are not permitted to modify locations for this image."
msgstr "You are not permitted to modify locations for this image."

#: glance/api/authorization.py:218
msgid "You are not permitted to modify this image."
msgstr "You are not permitted to modify this image."

#: glance/api/authorization.py:231
msgid "You are not permitted to modify tags on this image."
msgstr "You are not permitted to modify tags on this image."

#: glance/api/authorization.py:270
msgid "You are not permitted to delete this image."
msgstr "You are not permitted to delete this image."

#: glance/api/authorization.py:281
msgid "You are not permitted to upload data for this image."
msgstr "You are not permitted to upload data for this image."

#: glance/api/common.py:41
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"

#: glance/api/common.py:47
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"

#: glance/api/common.py:51
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "Corrupt image download for image %(image_id)s"

#: glance/api/common.py:76 glance/notifier/__init__.py:193
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr "An error occurred during image.send notification: %(err)s"

#: glance/api/policy.py:34
msgid "The location of the policy file."
msgstr "The location of the policy file."

#: glance/api/policy.py:36
msgid "The default policy to use."
msgstr "The default policy to use."

#: glance/api/policy.py:73
#, python-format
msgid "Loaded %(rule_type)spolicy rules: %(text_rules)s"
msgstr "Loaded %(rule_type)spolicy rules: %(text_rules)s"

#: glance/api/policy.py:85
msgid "Unable to find policy file"
msgstr "Unable to find policy file"

#: glance/api/policy.py:95
#, python-format
msgid "Loading policy from %s"
msgstr "Loading policy from %s"

#: glance/api/middleware/cache.py:57
msgid "Initialized image cache middleware"
msgstr "Initialized image cache middleware"

#: glance/api/middleware/cache.py:113
#, python-format
msgid "Cache hit for image '%s'"
msgstr "Cache hit for image '%s'"

#: glance/api/middleware/cache.py:120
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"

#: glance/api/middleware/cache.py:198
#, python-format
msgid "could not find %s"
msgstr "could not find %s"

#: glance/api/middleware/cache.py:206
#, python-format
msgid "Removing image %s from cache"
msgstr "Removing image %s from cache"

#: glance/api/middleware/cache.py:218
msgid "Checksum header is missing."
msgstr "Checksum header is missing."

#: glance/api/middleware/cache_manage.py:74
msgid "Initialized image cache management middleware"
msgstr "Initialized image cache management middleware"

#: glance/api/middleware/context.py:30
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."

#: glance/api/middleware/context.py:35
msgid "Role used to identify an authenticated user as administrator."
msgstr "Role used to identify an authenticated user as administrator."

#: glance/api/middleware/context.py:38
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."

#: glance/api/middleware/context.py:54
msgid "Unable to retrieve request id from context"
msgstr "Unable to retrieve request id from context"

#: glance/api/middleware/context.py:106
msgid "Invalid service catalog json."
msgstr "Invalid service catalog json."

#: glance/api/middleware/version_negotiation.py:43
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr "Determining version of request: %(method)s %(path)s Accept: %(accept)s"

#: glance/api/middleware/version_negotiation.py:55
msgid "Using media-type versioning"
msgstr "Using media-type versioning"

#: glance/api/middleware/version_negotiation.py:59
msgid "Using url versioning"
msgstr "Using url versioning"

#: glance/api/middleware/version_negotiation.py:66
msgid "Unknown version. Returning version choices."
msgstr "Unknown version. Returning version choices."

#: glance/api/middleware/version_negotiation.py:71
#, python-format
msgid "Matched version: v%d"
msgstr "Matched version: v%d"

#: glance/api/v1/controller.py:43 glance/api/v1/members.py:53
#, python-format
msgid "Image with identifier %s not found"
msgstr "Image with identifier %s not found"

#: glance/api/v1/controller.py:48
msgid "Forbidden image access"
msgstr "Forbidden image access"

#: glance/api/v1/controller.py:61
#, python-format
msgid "Image %s is not active"
msgstr "Image %s is not active"

#: glance/api/v1/controller.py:83
#, python-format
msgid "Store for image_id not found: %s"
msgstr "Store for image_id not found: %s"

#: glance/api/v1/images.py:80
#, python-format
msgid "Image name too long: %d"
msgstr "Image name too long: %d"

#: glance/api/v1/images.py:91
msgid ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."
msgstr ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."

#: glance/api/v1/images.py:281
#, python-format
msgid "External sourcing not supported for store %s"
msgstr "External sourcing not supported for store %s"

#: glance/api/v1/images.py:374
#, python-format
msgid "An image with identifier %s already exists"
msgstr "An image with identifier %s already exists"

#: glance/api/v1/images.py:381
#, python-format
msgid "Failed to reserve image. Got error: %(e)s"
msgstr "Failed to reserve image. Got error: %(e)s"

#: glance/api/v1/images.py:388
msgid "Forbidden to reserve image."
msgstr "Forbidden to reserve image."

#: glance/api/v1/images.py:415
#, python-format
msgid "Copy from external source failed: %s"
msgstr "Copy from external source failed: %s"

#: glance/api/v1/images.py:424
msgid "Content-Type must be application/octet-stream"
msgstr "Content-Type must be application/octet-stream"

#: glance/api/v1/images.py:435
#, python-format
msgid "Setting image %s to status 'saving'"
msgstr "Setting image %s to status 'saving'"

#: glance/api/v1/images.py:439
#, python-format
msgid "Uploading image data for image %(image_id)s to %(scheme)s store"
msgstr "Uploading image data for image %(image_id)s to %(scheme)s store"

#: glance/api/v1/images.py:452
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."

#: glance/api/v1/images.py:470
#, python-format
msgid ""
"Updating image %(image_id)s data. Checksum set to %(checksum)s, size set "
"to %(size)d"
msgstr ""
"Updating image %(image_id)s data. Checksum set to %(checksum)s, size set "
"to %(size)d"

#: glance/api/v1/images.py:483
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr "Attempt to upload duplicate image: %s"

#: glance/api/v1/images.py:489
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr "Forbidden upload attempt: %s"

#: glance/api/v1/images.py:497 glance/api/v2/image_data.py:72
#: glance/notifier/__init__.py:203
#, python-format
msgid "Image storage media is full: %s"
msgstr "Image storage media is full: %s"

#: glance/api/v1/images.py:505 glance/api/v2/image_data.py:78
#: glance/notifier/__init__.py:206
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "Insufficient permissions on image storage media: %s"

#: glance/api/v1/images.py:513 glance/api/v1/images.py:936
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "Denying attempt to upload image larger than %d bytes."

#: glance/api/v1/images.py:529
msgid "Failed to upload image"
msgstr "Failed to upload image"

#: glance/api/v1/images.py:554
#, python-format
msgid "Failed to activate image. Got error: %(e)s"
msgstr "Failed to activate image. Got error: %(e)s"

#: glance/api/v1/images.py:584
#, python-format
msgid "Unable to kill image %(id)s: %(exc)s"
msgstr "Unable to kill image %(id)s: %(exc)s"

#: glance/api/v1/images.py:619
msgid "Triggering asynchronous copy from external source"
msgstr "Triggering asynchronous copy from external source"

#: glance/api/v1/images.py:726
msgid "Forbidden to update deleted image."
msgstr "Forbidden to update deleted image."

#: glance/api/v1/images.py:744
msgid "Cannot upload to an unqueued image"
msgstr "Cannot upload to an unqueued image"

#: glance/api/v1/images.py:761
msgid "Attempted to update Location field for an image not in queued status."
msgstr "Attempted to update Location field for an image not in queued status."

#: glance/api/v1/images.py:782 glance/registry/api/v1/images.py:409
#, python-format
msgid "Failed to update image metadata. Got error: %(e)s"
msgstr "Failed to update image metadata. Got error: %(e)s"

#: glance/api/v1/images.py:789
#, python-format
msgid "Failed to find image to update: %(e)s"
msgstr "Failed to find image to update: %(e)s"

#: glance/api/v1/images.py:796
#, python-format
msgid "Forbidden to update image: %(e)s"
msgstr "Forbidden to update image: %(e)s"

#: glance/api/v1/images.py:835
msgid "Image is protected"
msgstr "Image is protected"

#: glance/api/v1/images.py:842
msgid "Forbidden to delete a deleted image."
msgstr "Forbidden to delete a deleted image."

#: glance/api/v1/images.py:866
#, python-format
msgid "Failed to find image to delete: %(e)s"
msgstr "Failed to find image to delete: %(e)s"

#: glance/api/v1/images.py:873
#, python-format
msgid "Forbidden to delete image: %(e)s"
msgstr "Forbidden to delete image: %(e)s"

#: glance/api/v1/images.py:896 glance/store/__init__.py:193
#, python-format
msgid "Store for scheme %s not found"
msgstr "Store for scheme %s not found"

#: glance/api/v1/images.py:912
#, python-format
msgid "Incoming image size of %s was not convertible to an integer."
msgstr "Incoming image size of %s was not convertible to an integer."

#: glance/api/v1/members.py:34 glance/registry/api/v1/members.py:34
msgid "No authenticated user"
msgstr "No authenticated user"

#: glance/api/v1/members.py:57
msgid "Unauthorized image access"
msgstr "Unauthorized image access"

#: glance/api/v2/image_data.py:59
#, python-format
msgid "Unable to upload duplicate image data for image: %s"
msgstr "Unable to upload duplicate image data for image: %s"

#: glance/api/v2/image_data.py:64
#, python-format
msgid "Not allowed to upload image data for image %s"
msgstr "Not allowed to upload image data for image %s"

#: glance/api/v2/image_data.py:84
msgid "Failed to upload image data due to HTTP error"
msgstr "Failed to upload image data due to HTTP error"

#: glance/api/v2/image_data.py:88
msgid "Failed to upload image data due to internal error"
msgstr "Failed to upload image data due to internal error"

#: glance/api/v2/image_data.py:102 glance/store/__init__.py:395
msgid "No image data could be found"
msgstr "No image data could be found"

#: glance/api/v2/image_members.py:164 glance/api/v2/images.py:190
msgid "Body expected in request."
msgstr "Body expected in request."

#: glance/api/v2/image_members.py:173
msgid "Member to be added not specified"
msgstr "Member to be added not specified"

#: glance/api/v2/image_members.py:182
msgid "Status not specified"
msgstr "Status not specified"

#: glance/api/v2/image_members.py:231
msgid "An identifier for the image member (tenantId)"
msgstr "An identifier for the image member (tenantId)"

#: glance/api/v2/image_members.py:235 glance/api/v2/images.py:485
msgid "An identifier for the image"
msgstr "An identifier for the image"

#: glance/api/v2/image_members.py:241
msgid "Date and time of image member creation"
msgstr "Date and time of image member creation"

#: glance/api/v2/image_members.py:248
msgid "Date and time of last modification of image member"
msgstr "Date and time of last modification of image member"

#: glance/api/v2/image_members.py:253
msgid "The status of this image member"
msgstr "The status of this image member"

#: glance/api/v2/images.py:118
#, python-format
msgid "Failed to find image %(image_id)s to update"
msgstr "Failed to find image %(image_id)s to update"

#: glance/api/v2/images.py:134 glance/api/v2/images.py:153
#, python-format
msgid "Property %s does not exist."
msgstr "Property %s does not exist."

#: glance/api/v2/images.py:141
#, python-format
msgid "Property %s already present."
msgstr "Property %s already present."

#: glance/api/v2/images.py:148
#, python-format
msgid "Property %s may not be removed."
msgstr "Property %s may not be removed."

#: glance/api/v2/images.py:222 glance/api/v2/images.py:244
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "Unable to find '%s' in JSON Schema change"

#: glance/api/v2/images.py:230
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."
msgstr ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."

#: glance/api/v2/images.py:235
msgid ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."
msgstr ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."

#: glance/api/v2/images.py:271
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "Pointer `%s` does not start with \"/\"."

#: glance/api/v2/images.py:274
#, python-format
msgid "Pointer `%s` contains more than one \"/\"."
msgstr "Pointer `%s` contains more than one \"/\"."

#: glance/api/v2/images.py:277
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr "Pointer `%s` contains \"~\" not part of a recognized escape sequence."

#: glance/api/v2/images.py:283
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "Operation \"%s\" requires a member named \"value\"."

#: glance/api/v2/images.py:313
msgid "Unrecognized JSON Schema draft version"
msgstr "Unrecognized JSON Schema draft version"

#: glance/api/v2/images.py:334
msgid "Request body must be a JSON array of operation objects."
msgstr "Request body must be a JSON array of operation objects."

#: glance/api/v2/images.py:339
msgid "Operations must be JSON objects."
msgstr "Operations must be JSON objects."

#: glance/api/v2/images.py:359 glance/registry/api/v1/images.py:209
msgid "limit param must be an integer"
msgstr "limit param must be an integer"

#: glance/api/v2/images.py:363 glance/registry/api/v1/images.py:212
msgid "limit param must be positive"
msgstr "limit param must be positive"

#: glance/api/v2/images.py:370
#, python-format
msgid "Invalid sort direction: %s"
msgstr "Invalid sort direction: %s"

#: glance/api/v2/images.py:377
#, python-format
msgid "Invalid status: %s"
msgstr "Invalid status: %s"

#: glance/api/v2/images.py:386
#, python-format
msgid "Invalid visibility value: %s"
msgstr "Invalid visibility value: %s"

#: glance/api/v2/images.py:491
msgid "Descriptive name for the image"
msgstr "Descriptive name for the image"

#: glance/api/v2/images.py:496
msgid "Status of the image"
msgstr "Status of the image"

#: glance/api/v2/images.py:502
msgid "Scope of image accessibility"
msgstr "Scope of image accessibility"

#: glance/api/v2/images.py:507
msgid "If true, image will not be deletable."
msgstr "If true, image will not be deletable."

#: glance/api/v2/images.py:511
msgid "md5 hash of image contents."
msgstr "md5 hash of image contents."

#: glance/api/v2/images.py:517
msgid "Size of image file in bytes"
msgstr "Size of image file in bytes"

#: glance/api/v2/images.py:534
msgid "Date and time of image registration"
msgstr "Date and time of image registration"

#: glance/api/v2/images.py:541
msgid "Date and time of the last image modification"
msgstr "Date and time of the last image modification"

#: glance/api/v2/images.py:546
msgid "List of strings related to the image"
msgstr "List of strings related to the image"

#: glance/api/v2/images.py:554
msgid "URL to access the image file kept in external store"
msgstr "URL to access the image file kept in external store"

#: glance/api/v2/images.py:559
msgid "Amount of ram (in MB) required to boot image."
msgstr "Amount of ram (in MB) required to boot image."

#: glance/api/v2/images.py:563
msgid "Amount of disk space (in GB) required to boot image."
msgstr "Amount of disk space (in GB) required to boot image."

#: glance/api/v2/images.py:603
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""
"Could not find schema properties file %s. Continuing without custom "
"properties"

#: glance/common/auth.py:186 glance/common/auth.py:224
#, python-format
msgid "Unexpected response: %s"
msgstr "Unexpected response: %s"

#: glance/common/auth.py:250
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "Unknown auth strategy '%s'"

#: glance/common/auth.py:271
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr "Encountered service with no \"type\": %s"

#: glance/common/client.py:236
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"

#: glance/common/client.py:244
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"

#: glance/common/client.py:253
#, python-format
msgid "The key file you specified %s does not exist"
msgstr "The key file you specified %s does not exist"

#: glance/common/client.py:260
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "The cert file you specified %s does not exist"

#: glance/common/client.py:267
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "The CA file you specified %s does not exist"

#: glance/common/client.py:305
#, python-format
msgid "Configuring from URL: %s"
msgstr "Configuring from URL: %s"

#: glance/common/client.py:317
#, python-format
msgid "Appending doc_root %(doc_root)s to URL %(url)s"
msgstr "Appending doc_root %(doc_root)s to URL %(url)s"

#: glance/common/client.py:396
#, python-format
msgid "Constructed URL: %s"
msgstr "Constructed URL: %s"

#: glance/common/config.py:36
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""

#: glance/common/config.py:42
msgid "Name of the paste configuration file."
msgstr "Name of the paste configuration file."

#: glance/common/config.py:46
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"

#: glance/common/config.py:49
msgid "Python module path of data access API"
msgstr "Python module path of data access API"

#: glance/common/config.py:51
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"

#: glance/common/config.py:54
msgid "Maximum permissible number of items that could be returned by a request"
msgstr "Maximum permissible number of items that could be returned by a request"

#: glance/common/config.py:57
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"

#: glance/common/config.py:61
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."

#: glance/common/config.py:64
msgid "Deploy the v1 OpenStack Images API. "
msgstr "Deploy the v1 OpenStack Images API. "

#: glance/common/config.py:66
msgid "Deploy the v2 OpenStack Images API. "
msgstr "Deploy the v2 OpenStack Images API. "

#: glance/common/config.py:68
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr "The hostname/IP of the pydev process listening for debug connections"

#: glance/common/config.py:71
msgid "The port on which a pydev process is listening for connections."
msgstr "The port on which a pydev process is listening for connections."

#: glance/common/config.py:74
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."

#: glance/common/config.py:135
msgid "Invalid syslog facility"
msgstr "Invalid syslog facility"

#: glance/common/config.py:209
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr "Loading %(app_name)s from %(conf_file)s"

#: glance/common/config.py:220
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"

#: glance/common/exception.py:39
msgid "An unknown exception occurred"
msgstr "An unknown exception occurred"

#: glance/common/exception.py:57
msgid "Missing required argument."
msgstr "Missing required argument."

#: glance/common/exception.py:61
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "Missing required credential: %(required)s"

#: glance/common/exception.py:65
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""

#: glance/common/exception.py:70
msgid "An object with the specified identifier was not found."
msgstr "An object with the specified identifier was not found."

#: glance/common/exception.py:74
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr "Unknown scheme '%(scheme)s' found in URI"

#: glance/common/exception.py:78
msgid "The Store URI was malformed."
msgstr "The Store URI was malformed."

#: glance/common/exception.py:82
msgid "An object with the same identifier already exists."
msgstr "An object with the same identifier already exists."

#: glance/common/exception.py:86
msgid "There is not enough disk space on the image storage media."
msgstr "There is not enough disk space on the image storage media."

#: glance/common/exception.py:90
msgid "Permission to write image storage media denied."
msgstr "Permission to write image storage media denied."

#: glance/common/exception.py:94
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "Connect error/bad request to Auth service at URL %(url)s."

#: glance/common/exception.py:98
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "Auth service at URL %(url)s not found."

#: glance/common/exception.py:102
msgid "Authorization failed."
msgstr "Authorization failed."

#: glance/common/exception.py:106
msgid "You are not authenticated."
msgstr "You are not authenticated."

#: glance/common/exception.py:110 glance/common/exception.py:114
#: glance/common/exception.py:123
msgid "You are not authorized to complete this action."
msgstr "You are not authorized to complete this action."

#: glance/common/exception.py:118
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "Image %(image_id)s is protected and cannot be deleted."

#: glance/common/exception.py:127
msgid "Data supplied was not valid."
msgstr "Data supplied was not valid."

#: glance/common/exception.py:131
msgid "Sort key supplied was not valid."
msgstr "Sort key supplied was not valid."

#: glance/common/exception.py:135
msgid "Unable to filter using the specified range."
msgstr "Unable to filter using the specified range."

#: glance/common/exception.py:139
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "Attribute '%(property)s' is read-only."

#: glance/common/exception.py:143
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "Attribute '%(property)s' is reserved."

#: glance/common/exception.py:147
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "Redirecting to %(uri)s for authorization."

#: glance/common/exception.py:151
msgid "There was an error migrating the database."
msgstr "There was an error migrating the database."

#: glance/common/exception.py:155
msgid "There was an error connecting to a server"
msgstr "There was an error connecting to a server"

#: glance/common/exception.py:159
msgid "There was an error configuring the client."
msgstr "There was an error configuring the client."

#: glance/common/exception.py:163
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"

#: glance/common/exception.py:169
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:180
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."

#: glance/common/exception.py:191
msgid "The request returned 500 Internal Server Error."
msgstr "The request returned 500 Internal Server Error."

#: glance/common/exception.py:195
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:200
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "Invalid content type %(content_type)s"

#: glance/common/exception.py:204
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr "Registry was not configured correctly on API server. Reason: %(reason)s"

#: glance/common/exception.py:209
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"

#: glance/common/exception.py:214
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"

#: glance/common/exception.py:219
msgid "Deleting images from this store is not supported."
msgstr "Deleting images from this store is not supported."

#: glance/common/exception.py:223
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr "Configuration for store failed. Adding images to this store is disabled."

#: glance/common/exception.py:228
#, python-format
msgid "'%(strategy)s' is not an available notifier strategy."
msgstr "'%(strategy)s' is not an available notifier strategy."

#: glance/common/exception.py:232
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "Maximum redirects (%(redirects)s) was exceeded."

#: glance/common/exception.py:236
msgid "Received invalid HTTP redirect."
msgstr "Received invalid HTTP redirect."

#: glance/common/exception.py:240
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Response from Keystone does not contain a Glance endpoint."

#: glance/common/exception.py:244
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."

#: glance/common/exception.py:250
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "Server worker creation failed: %(reason)s."

#: glance/common/exception.py:254
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "Unable to load schema: %(reason)s"

#: glance/common/exception.py:258
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "Provided object does not match schema '%(schema)s': %(reason)s"

#: glance/common/exception.py:263
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr "Provided header feature is unsupported: %(feature)s"

#: glance/common/exception.py:267
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."

#: glance/common/exception.py:272
msgid "The provided image is too large."
msgstr "The provided image is too large."

#: glance/common/utils.py:87
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr "Error: cooperative_iter exception %s"

#: glance/common/utils.py:409
msgid "Read-only access"
msgstr "Read-only access"

#: glance/common/utils.py:453
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: glance/common/wsgi.py:50
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."

#: glance/common/wsgi.py:53
msgid "The port on which the server will listen."
msgstr "The port on which the server will listen."

#: glance/common/wsgi.py:58
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr "The backlog value that will be used when creating the TCP listener socket."

#: glance/common/wsgi.py:61
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This isthe time in seconds"
" that the connection must be idle before TCP starts sending keepalive "
"probes."
msgstr ""
"The value for the socket option TCP_KEEPIDLE.  This isthe time in seconds"
" that the connection must be idle before TCP starts sending keepalive "
"probes."

#: glance/common/wsgi.py:64
msgid "CA certificate file to use to verify connecting clients."
msgstr "CA certificate file to use to verify connecting clients."

#: glance/common/wsgi.py:66
msgid "Certificate file to use when starting API server securely."
msgstr "Certificate file to use when starting API server securely."

#: glance/common/wsgi.py:68
msgid "Private key file to use when starting API server securely."
msgstr "Private key file to use when starting API server securely."

#: glance/common/wsgi.py:73
msgid ""
"The number of child process workers that will be created to service API "
"requests."
msgstr ""
"The number of child process workers that will be created to service API "
"requests."

#: glance/common/wsgi.py:126
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"

#: glance/common/wsgi.py:159
#, python-format
msgid "Could not bind to %s:%s after trying for 30 seconds"
msgstr "Could not bind to %s:%s after trying for 30 seconds"

#: glance/common/wsgi.py:214
#, python-format
msgid "Starting %d workers"
msgstr "Starting %d workers"

#: glance/common/wsgi.py:230
#, python-format
msgid "Removing dead child %s"
msgstr "Removing dead child %s"

#: glance/common/wsgi.py:233
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr "Not respawning child %d, cannot recover from termination"

#: glance/common/wsgi.py:237
msgid "All workers have terminated. Exiting"
msgstr "All workers have terminated. Exiting"

#: glance/common/wsgi.py:245
msgid "Caught keyboard interrupt. Exiting."
msgstr "Caught keyboard interrupt. Exiting."

#: glance/common/wsgi.py:249
msgid "Exited"
msgstr "Exited"

#: glance/common/wsgi.py:271
#, python-format
msgid "Child %d exiting normally"
msgstr "Child %d exiting normally"

#: glance/common/wsgi.py:276
#, python-format
msgid "Started child %s"
msgstr "Started child %s"

#: glance/common/wsgi.py:289
msgid "eventlet 'poll' hub is not available on this platform"
msgstr "eventlet 'poll' hub is not available on this platform"

#: glance/common/wsgi.py:304
msgid "Starting single process server"
msgstr "Starting single process server"

#: glance/common/wsgi.py:488
msgid "Malformed JSON in request body."
msgstr "Malformed JSON in request body."

#: glance/db/simple/api.py:37
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"

#: glance/db/simple/api.py:42
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr "Returning %(funcname)s: %(output)s"

#: glance/db/simple/api.py:174 glance/db/sqlalchemy/api.py:591
msgid "Unable to filter on a range with a non-numeric value."
msgstr "Unable to filter on a range with a non-numeric value."

#: glance/db/simple/api.py:236
#, python-format
msgid "Could not find image %s"
msgstr "Could not find image %s"

#: glance/db/simple/api.py:240
msgid "Unable to get deleted image"
msgstr "Unable to get deleted image"

#: glance/db/simple/api.py:244
msgid "Unable to get unowned image"
msgstr "Unable to get unowned image"

#: glance/db/sqlalchemy/api.py:54
msgid ""
"Period in seconds after which SQLAlchemy should reestablish its "
"connection to the database."
msgstr ""
"Period in seconds after which SQLAlchemy should reestablish its "
"connection to the database."

#: glance/db/sqlalchemy/api.py:57
msgid "The number of times to retry a connection to the SQLserver."
msgstr "The number of times to retry a connection to the SQLserver."

#: glance/db/sqlalchemy/api.py:60
msgid ""
"The amount of time to wait (in seconds) before attempting to retry the "
"SQL connection."
msgstr ""
"The amount of time to wait (in seconds) before attempting to retry the "
"SQL connection."

#: glance/db/sqlalchemy/api.py:63
msgid "A boolean that determines if the database will be automatically created."
msgstr "A boolean that determines if the database will be automatically created."

#: glance/db/sqlalchemy/api.py:119
msgid "Attempted to modify image user did not own."
msgstr "Attempted to modify image user did not own."

#: glance/db/sqlalchemy/api.py:120
msgid "You do not own this image"
msgstr "You do not own this image"

#: glance/db/sqlalchemy/api.py:166
#, python-format
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: %s"
msgstr ""
"Error configuring registry database with supplied sql_connection. Got "
"error: %s"

#: glance/db/sqlalchemy/api.py:176
msgid "auto-creating glance registry DB"
msgstr "auto-creating glance registry DB"

#: glance/db/sqlalchemy/api.py:184
msgid "not auto-creating glance registry DB"
msgstr "not auto-creating glance registry DB"

#: glance/db/sqlalchemy/api.py:223
#, python-format
msgid "SQL connection failed. %d attempts left."
msgstr "SQL connection failed. %d attempts left."

#: glance/db/sqlalchemy/api.py:431
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id not in sort_keys; is sort_keys unique?"

#: glance/db/sqlalchemy/api.py:479
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Unknown sort direction, must be 'desc' or 'asc'"

#: glance/db/sqlalchemy/migration.py:49
msgid "database is not under migration control"
msgstr "database is not under migration control"

#: glance/db/sqlalchemy/migration.py:64
#, python-format
msgid "Upgrading database to version %s"
msgstr "Upgrading database to version %s"

#: glance/db/sqlalchemy/migration.py:79
#, python-format
msgid "Downgrading database to version %s"
msgstr "Downgrading database to version %s"

#: glance/db/sqlalchemy/migration.py:92
msgid "database is already under migration control"
msgstr "database is already under migration control"

#: glance/db/sqlalchemy/migrate_repo/schema.py:95
#, python-format
msgid "creating table %(table)s"
msgstr "creating table %(table)s"

#: glance/db/sqlalchemy/migrate_repo/schema.py:101
#, python-format
msgid "dropping table %(table)s"
msgstr "dropping table %(table)s"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:107
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:146
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:114
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:153
#: glance/store/s3.py:125
#, python-format
msgid "Invalid store uri %(uri)s: %(reason)s"
msgstr "Invalid store uri %(uri)s: %(reason)s"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:144
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:184
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr "Badly formed credentials '%(creds)s' in Swift URI"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:166
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:215
#: glance/store/s3.py:167
#, python-format
msgid "Badly formed S3 URI: %s"
msgstr "Badly formed S3 URI: %s"

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:68
msgid ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."
msgstr ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:88
#, python-format
msgid "Failed to decrypt location value for image %s"
msgstr "Failed to decrypt location value for image %s"

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:197
#: glance/store/swift.py:201
msgid "Badly formed credentials in Swift URI."
msgstr "Badly formed credentials in Swift URI."

#: glance/domain/__init__.py:103
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "Property %s must be set prior to saving data."

#: glance/domain/__init__.py:105
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "Properties %s must be set prior to saving data."

#: glance/domain/__init__.py:158
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "Status must be \"pending\", \"accepted\" or \"rejected\"."

#: glance/image_cache/__init__.py:35
msgid "The driver to use for image cache management."
msgstr "The driver to use for image cache management."

#: glance/image_cache/__init__.py:37
msgid "The maximum size in bytes that the cache can use."
msgstr "The maximum size in bytes that the cache can use."

#: glance/image_cache/__init__.py:39
msgid ""
"The amount of time to let an image remain in the cache without being "
"accessed"
msgstr ""
"The amount of time to let an image remain in the cache without being "
"accessed"

#: glance/image_cache/__init__.py:42
msgid "Base directory that the Image Cache uses."
msgstr "Base directory that the Image Cache uses."

#: glance/image_cache/__init__.py:66
#, python-format
msgid "Image cache loaded driver '%s'."
msgstr "Image cache loaded driver '%s'."

#: glance/image_cache/__init__.py:69
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."

#: glance/image_cache/__init__.py:74 glance/image_cache/__init__.py:91
msgid "Defaulting to SQLite driver."
msgstr "Defaulting to SQLite driver."

#: glance/image_cache/__init__.py:88
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"

#: glance/image_cache/__init__.py:173
msgid "Image cache has free space, skipping prune..."
msgstr "Image cache has free space, skipping prune..."

#: glance/image_cache/__init__.py:177
#, python-format
msgid ""
"Image cache currently %(overage)d bytes over max size. Starting prune to "
"max size of %(max_size)d "
msgstr ""
"Image cache currently %(overage)d bytes over max size. Starting prune to "
"max size of %(max_size)d "

#: glance/image_cache/__init__.py:186
#, python-format
msgid "Pruning '%(image_id)s' to free %(size)d bytes"
msgstr "Pruning '%(image_id)s' to free %(size)d bytes"

#: glance/image_cache/__init__.py:194
#, python-format
msgid ""
"Pruning finished pruning. Pruned %(total_files_pruned)d and "
"%(total_bytes_pruned)d."
msgstr ""
"Pruning finished pruning. Pruned %(total_files_pruned)d and "
"%(total_bytes_pruned)d."

#: glance/image_cache/__init__.py:231
#, python-format
msgid "Tee'ing image '%s' into cache"
msgstr "Tee'ing image '%s' into cache"

#: glance/image_cache/__init__.py:248
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr "Checksum verification failed. Aborted caching of image '%s'."

#: glance/image_cache/__init__.py:258
#, python-format
msgid ""
"Exception encountered while tee'ing image '%s' into cache: %s. Continuing"
" with response."
msgstr ""
"Exception encountered while tee'ing image '%s' into cache: %s. Continuing"
" with response."

#: glance/image_cache/prefetcher.py:48
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr "Image '%s' is not active. Not caching."

#: glance/image_cache/prefetcher.py:53
#, python-format
msgid "No metadata found for image '%s'"
msgstr "No metadata found for image '%s'"

#: glance/image_cache/prefetcher.py:58
#, python-format
msgid "Caching image '%s'"
msgstr "Caching image '%s'"

#: glance/image_cache/prefetcher.py:66
msgid "Nothing to prefetch."
msgstr "Nothing to prefetch."

#: glance/image_cache/prefetcher.py:70
#, python-format
msgid "Found %d images to prefetch"
msgstr "Found %d images to prefetch"

#: glance/image_cache/prefetcher.py:76
msgid "Failed to successfully cache all images in queue."
msgstr "Failed to successfully cache all images in queue."

#: glance/image_cache/prefetcher.py:80
#, python-format
msgid "Successfully cached all %d images"
msgstr "Successfully cached all %d images"

#: glance/image_cache/drivers/base.py:56
#, python-format
msgid "Failed to read %s from config"
msgstr "Failed to read %s from config"

#: glance/image_cache/drivers/sqlite.py:40
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""
"The path to the sqlite file database that will be used for image cache "
"management."

#: glance/image_cache/drivers/sqlite.py:122
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr "Failed to initialize the image cache database. Got error: %s"

#: glance/image_cache/drivers/sqlite.py:161
#: glance/image_cache/drivers/xattr.py:145
msgid "Gathering cached image entries."
msgstr "Gathering cached image entries."

#: glance/image_cache/drivers/sqlite.py:300
#: glance/image_cache/drivers/xattr.py:275
#, python-format
msgid "Fetch finished, moving '%(incomplete_path)s' to '%(final_path)s'"
msgstr "Fetch finished, moving '%(incomplete_path)s' to '%(final_path)s'"

#: glance/image_cache/drivers/sqlite.py:324
#: glance/image_cache/drivers/xattr.py:291
#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"

#: glance/image_cache/drivers/sqlite.py:386
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr "Error executing SQLite call. Got error: %s"

#: glance/image_cache/drivers/sqlite.py:402
#: glance/image_cache/drivers/xattr.py:337
#, python-format
msgid "Not queueing image '%s'. Already cached."
msgstr "Not queueing image '%s'. Already cached."

#: glance/image_cache/drivers/sqlite.py:407
#: glance/image_cache/drivers/xattr.py:342
#, python-format
msgid "Not queueing image '%s'. Already being written to cache"
msgstr "Not queueing image '%s'. Already being written to cache"

#: glance/image_cache/drivers/sqlite.py:413
#: glance/image_cache/drivers/xattr.py:348
#, python-format
msgid "Not queueing image '%s'. Already queued."
msgstr "Not queueing image '%s'. Already queued."

#: glance/image_cache/drivers/sqlite.py:431
#, python-format
msgid "Removed invalid cache file %s"
msgstr "Removed invalid cache file %s"

#: glance/image_cache/drivers/sqlite.py:443
#, python-format
msgid "Removed stalled cache file %s"
msgstr "Removed stalled cache file %s"

#: glance/image_cache/drivers/sqlite.py:474
#: glance/image_cache/drivers/xattr.py:437
#, python-format
msgid "Deleting image cache file '%s'"
msgstr "Deleting image cache file '%s'"

#: glance/image_cache/drivers/sqlite.py:477
#: glance/image_cache/drivers/xattr.py:440
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr "Cached image file '%s' doesn't exist, unable to delete"

#: glance/image_cache/drivers/xattr.py:106
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."
msgstr ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."

#: glance/image_cache/drivers/xattr.py:283
#, python-format
msgid "Removing image '%s' from queue after caching it."
msgstr "Removing image '%s' from queue after caching it."

#: glance/image_cache/drivers/xattr.py:353
#, python-format
msgid "Queueing image '%s'."
msgstr "Queueing image '%s'."

#: glance/image_cache/drivers/xattr.py:383
#, python-format
msgid "No grace period, reaping '%(path)s' immediately"
msgstr "No grace period, reaping '%(path)s' immediately"

#: glance/image_cache/drivers/xattr.py:388
#, python-format
msgid "Cache entry '%(path)s' exceeds grace period, (%(age)i s > %(grace)i s)"
msgstr "Cache entry '%(path)s' exceeds grace period, (%(age)i s > %(grace)i s)"

#: glance/image_cache/drivers/xattr.py:393
#, python-format
msgid "Reaped %(reaped)s %(entry_type)s cache entries"
msgstr "Reaped %(reaped)s %(entry_type)s cache entries"

#: glance/notifier/__init__.py:33
msgid ""
"Notifications can be sent when images are create, updated or deleted. "
"There are three methods of sending notifications, logging (via the "
"log_file directive), rabbit (via a rabbitmq queue), qpid (via a Qpid "
"message queue), or noop (no notifications sent, the default)."
msgstr ""
"Notifications can be sent when images are create, updated or deleted. "
"There are three methods of sending notifications, logging (via the "
"log_file directive), rabbit (via a rabbitmq queue), qpid (via a Qpid "
"message queue), or noop (no notifications sent, the default)."

#: glance/notifier/__init__.py:62
#, python-format
msgid "Converted strategy alias %s to %s"
msgstr "Converted strategy alias %s to %s"

#: glance/notifier/__init__.py:66
#, python-format
msgid "No strategy alias found for %s"
msgstr "No strategy alias found for %s"

#: glance/notifier/notify_kombu.py:31
msgid "The host name of the rabbitmq server"
msgstr "The host name of the rabbitmq server"

#: glance/notifier/notify_kombu.py:33
msgid "The port on which the rabbitmq server is listening"
msgstr "The port on which the rabbitmq server is listening"

#: glance/notifier/notify_kombu.py:35
msgid "A boolean value indicating if the selected rabbitmq server uses SSL."
msgstr "A boolean value indicating if the selected rabbitmq server uses SSL."

#: glance/notifier/notify_kombu.py:38
msgid "The user ID for authentication with rabbitmq."
msgstr "The user ID for authentication with rabbitmq."

#: glance/notifier/notify_kombu.py:40
msgid ""
"The password that will be used for authentication with the rabbitmq "
"server."
msgstr ""
"The password that will be used for authentication with the rabbitmq "
"server."

#: glance/notifier/notify_kombu.py:43
msgid "The virtual host used in the rabbitmq connection."
msgstr "The virtual host used in the rabbitmq connection."

#: glance/notifier/notify_kombu.py:45
msgid "Exchange name to use for connection when using rabbit strategy."
msgstr "Exchange name to use for connection when using rabbit strategy."

#: glance/notifier/notify_kombu.py:48
msgid "Topic to use for connection when using rabbit strategy."
msgstr "Topic to use for connection when using rabbit strategy."

#: glance/notifier/notify_kombu.py:51
msgid "The maximum number of times to attempt to connect to the AMQP server."
msgstr "The maximum number of times to attempt to connect to the AMQP server."

#: glance/notifier/notify_kombu.py:54
msgid ""
"This value multiplied by the number of connection attempts gives the "
"amount of time in seconds to sleep between connection attempts to the "
"AMQP server."
msgstr ""
"This value multiplied by the number of connection attempts gives the "
"amount of time in seconds to sleep between connection attempts to the "
"AMQP server."

#: glance/notifier/notify_kombu.py:58
msgid ""
"The maximum amount of time to wait between connection attempts.  The "
"delay time will be the smaller of this value and the value of "
"<rabbit_retry_backoff> * <the number of failed connection attempts so "
"far>."
msgstr ""
"The maximum amount of time to wait between connection attempts.  The "
"delay time will be the smaller of this value and the value of "
"<rabbit_retry_backoff> * <the number of failed connection attempts so "
"far>."

#: glance/notifier/notify_kombu.py:110
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr "Reconnecting to AMQP server on %(hostname)s:%(port)d"

#: glance/notifier/notify_kombu.py:114
#, python-format
msgid "Connecting to AMQP server on %(hostname)s:%(port)d"
msgstr "Connecting to AMQP server on %(hostname)s:%(port)d"

#: glance/notifier/notify_kombu.py:144
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr "Connected to AMQP server on %(hostname)s:%(port)d"

#: glance/notifier/notify_kombu.py:173
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"

#: glance/notifier/notify_kombu.py:185
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."

#: glance/notifier/notify_kombu.py:192
#, python-format
msgid "Notification with priority %(priority)s failed: msg=%(msg)s"
msgstr "Notification with priority %(priority)s failed: msg=%(msg)s"

#: glance/notifier/notify_kombu.py:231
#, python-format
msgid "Unable to send notification: %s"
msgstr "Unable to send notification: %s"

#: glance/notifier/notify_qpid.py:110
#, python-format
msgid "Connected to AMQP server on %s"
msgstr "Connected to AMQP server on %s"

#: glance/openstack/common/jsonutils.py:88
#, python-format
msgid "Max serialization depth exceeded on object: %d %s"
msgstr "Max serialization depth exceeded on object: %d %s"

#: glance/openstack/common/log.py:225
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecated: %s"

#: glance/openstack/common/log.py:358
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog facility must be one of: %s"

#: glance/openstack/common/log.py:518
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatal call to deprecated config: %(msg)s"

#: glance/openstack/common/policy.py:394
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr "Failed to understand rule %(rule)s"

#: glance/openstack/common/policy.py:404
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: glance/openstack/common/policy.py:679
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr "Failed to understand rule %(rule)r"

#: glance/openstack/common/notifier/api.py:126
#, python-format
msgid "%s not in valid priorities"
msgstr "%s not in valid priorities"

#: glance/openstack/common/notifier/api.py:142
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"

#: glance/openstack/common/notifier/api.py:172
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr "Failed to load notifier %s. These notifications will not be sent."

#: glance/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."

#: glance/openstack/common/notifier/rpc_notifier.py:45
#: glance/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr "Could not send notification to %(topic)s. Payload=%(message)s"

#: glance/registry/__init__.py:34
msgid "Address to find the registry server."
msgstr "Address to find the registry server."

#: glance/registry/__init__.py:36
msgid "Port the registry server is listening on."
msgstr "Port the registry server is listening on."

#: glance/registry/__init__.py:40
msgid ""
"The protocol to use for communication with the registry server.  Either "
"http or https."
msgstr ""
"The protocol to use for communication with the registry server.  Either "
"http or https."

#: glance/registry/__init__.py:43
msgid "The path to the key file to use in SSL connections to the registry server."
msgstr "The path to the key file to use in SSL connections to the registry server."

#: glance/registry/__init__.py:46
msgid ""
"The path to the cert file to use in SSL connections to the registry "
"server."
msgstr ""
"The path to the cert file to use in SSL connections to the registry "
"server."

#: glance/registry/__init__.py:49
msgid ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."
msgstr ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."

#: glance/registry/__init__.py:52
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."
msgstr ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."

#: glance/registry/__init__.py:56
msgid ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."
msgstr ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."

#: glance/registry/__init__.py:62
msgid "The administrators user name."
msgstr "The administrators user name."

#: glance/registry/__init__.py:64
msgid "The administrators password."
msgstr "The administrators password."

#: glance/registry/__init__.py:66
msgid "The tenant name of the adminstrative user."
msgstr "The tenant name of the adminstrative user."

#: glance/registry/__init__.py:68
msgid "The URL to the keystone service."
msgstr "The URL to the keystone service."

#: glance/registry/__init__.py:70
msgid "The strategy to use for authentication."
msgstr "The strategy to use for authentication."

#: glance/registry/__init__.py:72
msgid "The region for the authentication service."
msgstr "The region for the authentication service."

#: glance/registry/__init__.py:97
msgid "Configuration option was not valid"
msgstr "Configuration option was not valid"

#: glance/registry/__init__.py:101
msgid "Could not find required configuration option"
msgstr "Could not find required configuration option"

#: glance/registry/__init__.py:164
msgid "Adding image metadata..."
msgstr "Adding image metadata..."

#: glance/registry/__init__.py:171
#, python-format
msgid "Updating image metadata for image %s..."
msgstr "Updating image metadata for image %s..."

#: glance/registry/__init__.py:177
#, python-format
msgid "Deleting image metadata for image %s..."
msgstr "Deleting image metadata for image %s..."

#: glance/registry/client.py:93
#, python-format
msgid ""
"Registry request %(method)s %(action)s HTTP %(status)s request id "
"%(request_id)s"
msgstr ""
"Registry request %(method)s %(action)s HTTP %(status)s request id "
"%(request_id)s"

#: glance/registry/client.py:99
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr "Registry client request %(method)s %(action)s raised %(exc_name)s"

#: glance/registry/api/v1/images.py:74
msgid "Invalid marker. Image could not be found."
msgstr "Invalid marker. Image could not be found."

#: glance/registry/api/v1/images.py:107
msgid "Returning image list"
msgstr "Returning image list"

#: glance/registry/api/v1/images.py:126
msgid "Returning detailed image list"
msgstr "Returning detailed image list"

#: glance/registry/api/v1/images.py:179
msgid "Unrecognized changes-since value"
msgstr "Unrecognized changes-since value"

#: glance/registry/api/v1/images.py:184
msgid "protected must be True, or False"
msgstr "protected must be True, or False"

#: glance/registry/api/v1/images.py:221
msgid "Invalid marker format"
msgstr "Invalid marker format"

#: glance/registry/api/v1/images.py:231
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "Unsupported sort_key. Acceptable values: %s"

#: glance/registry/api/v1/images.py:240
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "Unsupported sort_dir. Acceptable values: %s"

#: glance/registry/api/v1/images.py:266
msgid "is_public must be None, True, or False"
msgstr "is_public must be None, True, or False"

#: glance/registry/api/v1/images.py:282
#, python-format
msgid "Successfully retrieved image %(id)s"
msgstr "Successfully retrieved image %(id)s"

#: glance/registry/api/v1/images.py:285 glance/registry/api/v1/images.py:324
#: glance/registry/api/v1/images.py:414 glance/registry/api/v1/members.py:47
#: glance/registry/api/v1/members.py:81 glance/registry/api/v1/members.py:194
#: glance/registry/api/v1/members.py:254
#, python-format
msgid "Image %(id)s not found"
msgstr "Image %(id)s not found"

#: glance/registry/api/v1/images.py:291 glance/registry/api/v1/images.py:320
#: glance/registry/api/v1/images.py:426 glance/registry/api/v1/members.py:53
#: glance/registry/api/v1/members.py:87 glance/registry/api/v1/members.py:200
#: glance/registry/api/v1/members.py:260
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr "Access denied to image %(id)s but returning 'not found'"

#: glance/registry/api/v1/images.py:310
#, python-format
msgid "Successfully deleted image %(id)s"
msgstr "Successfully deleted image %(id)s"

#: glance/registry/api/v1/images.py:314
#, python-format
msgid "Delete denied for public image %(id)s"
msgstr "Delete denied for public image %(id)s"

#: glance/registry/api/v1/images.py:351
#, python-format
msgid "Rejecting image creation request for invalid image id '%(bad_id)s'"
msgstr "Rejecting image creation request for invalid image id '%(bad_id)s'"

#: glance/registry/api/v1/images.py:354
msgid "Invalid image id format"
msgstr "Invalid image id format"

#: glance/registry/api/v1/images.py:362
#, python-format
msgid "Successfully created image %(id)s"
msgstr "Successfully created image %(id)s"

#: glance/registry/api/v1/images.py:366
#, python-format
msgid "Image with identifier %s already exists!"
msgstr "Image with identifier %s already exists!"

#: glance/registry/api/v1/images.py:370
#, python-format
msgid "Failed to add image metadata. Got error: %(e)s"
msgstr "Failed to add image metadata. Got error: %(e)s"

#: glance/registry/api/v1/images.py:397
#, python-format
msgid "Updating image %(id)s with metadata: %(image_data)r"
msgstr "Updating image %(id)s with metadata: %(image_data)r"

#: glance/registry/api/v1/images.py:405
#, python-format
msgid "Updating metadata for image %(id)s"
msgstr "Updating metadata for image %(id)s"

#: glance/registry/api/v1/images.py:420
#, python-format
msgid "Update denied for public image %(id)s"
msgstr "Update denied for public image %(id)s"

#: glance/registry/api/v1/members.py:58
#, python-format
msgid "Returning member list for image %(id)s"
msgstr "Returning member list for image %(id)s"

#: glance/registry/api/v1/members.py:93 glance/registry/api/v1/members.py:206
#: glance/registry/api/v1/members.py:266
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr "User lacks permission to share image %(id)s"

#: glance/registry/api/v1/members.py:95 glance/registry/api/v1/members.py:208
#: glance/registry/api/v1/members.py:268
msgid "No permission to share that image"
msgstr "No permission to share that image"

#: glance/registry/api/v1/members.py:103 glance/registry/api/v1/members.py:119
#: glance/registry/api/v1/members.py:218
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr "Invalid membership association specified for image %(id)s"

#: glance/registry/api/v1/members.py:106 glance/registry/api/v1/members.py:122
#: glance/registry/api/v1/members.py:221
#, python-format
msgid "Invalid membership association: %s"
msgstr "Invalid membership association: %s"

#: glance/registry/api/v1/members.py:170
#, python-format
msgid "Successfully updated memberships for image %(id)s"
msgstr "Successfully updated memberships for image %(id)s"

#: glance/registry/api/v1/members.py:239
#, python-format
msgid "Successfully updated a membership for image %(id)s"
msgstr "Successfully updated a membership for image %(id)s"

#: glance/registry/api/v1/members.py:278
#, python-format
msgid "%(id)s is not a member of image %(image_id)s"
msgstr "%(id)s is not a member of image %(image_id)s"

#: glance/registry/api/v1/members.py:280 glance/registry/api/v1/members.py:297
msgid "Membership could not be found."
msgstr "Membership could not be found."

#: glance/registry/api/v1/members.py:284
#, python-format
msgid "Successfully deleted a membership from image %(id)s"
msgstr "Successfully deleted a membership from image %(id)s"

#: glance/registry/api/v1/members.py:295
#, python-format
msgid "Member %(id)s not found"
msgstr "Member %(id)s not found"

#: glance/registry/api/v1/members.py:300
#, python-format
msgid "Returning list of images shared with member %(id)s"
msgstr "Returning list of images shared with member %(id)s"

#: glance/store/__init__.py:44
msgid ""
"List of which store classes and store class locations are currently known"
" to glance at startup."
msgstr ""
"List of which store classes and store class locations are currently known"
" to glance at startup."

#: glance/store/__init__.py:47
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."
msgstr ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."

#: glance/store/__init__.py:52
msgid ""
"Directory that the scrubber will use to track information about what to "
"delete.  Make sure this is also set in glance-api.conf"
msgstr ""
"Directory that the scrubber will use to track information about what to "
"delete.  Make sure this is also set in glance-api.conf"

#: glance/store/__init__.py:56
msgid "Turn on/off delayed delete."
msgstr "Turn on/off delayed delete."

#: glance/store/__init__.py:58
msgid "The amount of time in seconds to delay before performing a delete."
msgstr "The amount of time in seconds to delay before performing a delete."

#: glance/store/__init__.py:267
#, python-format
msgid "Failed to delete image in store at URI: %s"
msgstr "Failed to delete image in store at URI: %s"

#: glance/store/__init__.py:273
#, python-format
msgid "Failed to delete image at %s from store (%s)"
msgstr "Failed to delete image at %s from store (%s)"

#: glance/store/__init__.py:286
#, python-format
msgid "Image id %(image_id)s already queued for delete"
msgstr "Image id %(image_id)s already queued for delete"

#: glance/store/__init__.py:312
msgid "Skipping store.set_acls... not implemented."
msgstr "Skipping store.set_acls... not implemented."

#: glance/store/base.py:43
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr "Failed to configure store correctly: %s Disabling add method."

#: glance/store/filesystem.py:39
msgid "Directory to which the Filesystem backend store writes images."
msgstr "Directory to which the Filesystem backend store writes images."

#: glance/store/filesystem.py:68
#, python-format
msgid "No path specified in URI: %s"
msgstr "No path specified in URI: %s"

#: glance/store/filesystem.py:120
#, python-format
msgid "Could not find %s in configuration options."
msgstr "Could not find %s in configuration options."

#: glance/store/filesystem.py:127
#, python-format
msgid "Directory to write image files does not exist (%s). Creating."
msgstr "Directory to write image files does not exist (%s). Creating."

#: glance/store/filesystem.py:138
#, python-format
msgid "Unable to create datadir: %s"
msgstr "Unable to create datadir: %s"

#: glance/store/filesystem.py:148
#, python-format
msgid "Image file %s not found"
msgstr "Image file %s not found"

#: glance/store/filesystem.py:164
#, python-format
msgid "Found image at %s. Returning in ChunkedFile."
msgstr "Found image at %s. Returning in ChunkedFile."

#: glance/store/filesystem.py:179
#, python-format
msgid "Found image at %s."
msgstr "Found image at %s."

#: glance/store/filesystem.py:198
#, python-format
msgid "Deleting image at %(fn)s"
msgstr "Deleting image at %(fn)s"

#: glance/store/filesystem.py:201
#, python-format
msgid "You cannot delete file %s"
msgstr "You cannot delete file %s"

#: glance/store/filesystem.py:203
#, python-format
msgid "Image file %s does not exist"
msgstr "Image file %s does not exist"

#: glance/store/filesystem.py:228
#, python-format
msgid "Image file %s already exists!"
msgstr "Image file %s already exists!"

#: glance/store/filesystem.py:253
#, python-format
msgid ""
"Wrote %(bytes_written)d bytes to %(filepath)s with checksum "
"%(checksum_hex)s"
msgstr ""
"Wrote %(bytes_written)d bytes to %(filepath)s with checksum "
"%(checksum_hex)s"

#: glance/store/filesystem.py:262
#, python-format
msgid "Unable to remove partial image data for image %s: %s"
msgstr "Unable to remove partial image data for image %s: %s"

#: glance/store/http.py:82
#, python-format
msgid "Credentials '%s' not well-formatted."
msgstr "Credentials '%s' not well-formatted."

#: glance/store/http.py:89
msgid "No address specified in HTTP URL"
msgstr "No address specified in HTTP URL"

#: glance/store/http.py:164
#, python-format
msgid "HTTP URL returned a %s status code."
msgstr "HTTP URL returned a %s status code."

#: glance/store/http.py:170
msgid "The HTTP URL attempted to redirect with an invalid status code."
msgstr "The HTTP URL attempted to redirect with an invalid status code."

#: glance/store/rbd.py:51
msgid ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."
msgstr ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."

#: glance/store/rbd.py:55
msgid "RADOS pool in which images are stored."
msgstr "RADOS pool in which images are stored."

#: glance/store/rbd.py:57
msgid "RADOS user to authenticate as (only applicable if using cephx.)"
msgstr "RADOS user to authenticate as (only applicable if using cephx.)"

#: glance/store/rbd.py:60
msgid "Ceph configuration file path."
msgstr "Ceph configuration file path."

#: glance/store/rbd.py:102
msgid "URI must start with rbd://"
msgstr "URI must start with rbd://"

#: glance/store/rbd.py:103 glance/store/rbd.py:110 glance/store/rbd.py:121
#: glance/store/rbd.py:125
#, python-format
msgid "Invalid URI: %(uri)s: %(reason)s"
msgstr "Invalid URI: %(uri)s: %(reason)s"

#: glance/store/rbd.py:109
msgid "URI contains non-ascii characters"
msgstr "URI contains non-ascii characters"

#: glance/store/rbd.py:120
msgid "URI must have exactly 1 or 4 components"
msgstr "URI must have exactly 1 or 4 components"

#: glance/store/rbd.py:124
msgid "URI cannot contain empty components"
msgstr "URI cannot contain empty components"

#: glance/store/rbd.py:158 glance/store/rbd.py:297
#, python-format
msgid "RBD image %s does not exist"
msgstr "RBD image %s does not exist"

#: glance/store/rbd.py:185
#, python-format
msgid "Error in store configuration: %s"
msgstr "Error in store configuration: %s"

#: glance/store/rbd.py:254
#, python-format
msgid "RBD image %s already exists"
msgstr "RBD image %s already exists"

#: glance/store/rbd.py:288
#, python-format
msgid "snapshot %s@%s could not be unprotected because it is in use"
msgstr "snapshot %s@%s could not be unprotected because it is in use"

#: glance/store/rbd.py:299
#, python-format
msgid "image %s could not be removedbecause it is in use"
msgstr "image %s could not be removedbecause it is in use"

#: glance/store/s3.py:39
msgid "The host where the S3 server is listening."
msgstr "The host where the S3 server is listening."

#: glance/store/s3.py:41
msgid "The S3 query token access key."
msgstr "The S3 query token access key."

#: glance/store/s3.py:43
msgid "The S3 query token secret key."
msgstr "The S3 query token secret key."

#: glance/store/s3.py:45
msgid "The S3 bucket to be used to store the Glance data."
msgstr "The S3 bucket to be used to store the Glance data."

#: glance/store/s3.py:47
msgid ""
"The local directory where uploads will be staged before they are "
"transfered into S3."
msgstr ""
"The local directory where uploads will be staged before they are "
"transfered into S3."

#: glance/store/s3.py:50
msgid ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."
msgstr ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."

#: glance/store/s3.py:54
msgid ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."
msgstr ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."

#: glance/store/s3.py:117
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"
msgstr ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"

#: glance/store/s3.py:151
#, python-format
msgid "Badly formed S3 credentials %s"
msgstr "Badly formed S3 credentials %s"

#: glance/store/s3.py:164
msgid "Badly formed S3 URI. Missing s3 service URL."
msgstr "Badly formed S3 URI. Missing s3 service URL."

#: glance/store/s3.py:253 glance/store/swift.py:308
#, python-format
msgid "Could not find %(param)s in configuration options."
msgstr "Could not find %(param)s in configuration options."

#: glance/store/s3.py:308
#, python-format
msgid ""
"Retrieved image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""
"Retrieved image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"

#: glance/store/s3.py:367
#, python-format
msgid "S3 already has an image at location %s"
msgstr "S3 already has an image at location %s"

#: glance/store/s3.py:371
#, python-format
msgid ""
"Adding image object to S3 using (s3_host=%(s3_host)s, "
"access_key=%(access_key)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""
"Adding image object to S3 using (s3_host=%(s3_host)s, "
"access_key=%(access_key)s, bucket=%(bucket)s, key=%(obj_name)s)"

#: glance/store/s3.py:393
#, python-format
msgid "Writing request body file to temporary file for %s"
msgstr "Writing request body file to temporary file for %s"

#: glance/store/s3.py:405
#, python-format
msgid "Uploading temporary file to S3 for %s"
msgstr "Uploading temporary file to S3 for %s"

#: glance/store/s3.py:414
#, python-format
msgid ""
"Wrote %(size)d bytes to S3 key named %(obj_name)s with checksum "
"%(checksum_hex)s"
msgstr ""
"Wrote %(size)d bytes to S3 key named %(obj_name)s with checksum "
"%(checksum_hex)s"

#: glance/store/s3.py:440
#, python-format
msgid ""
"Deleting image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""
"Deleting image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"

#: glance/store/s3.py:462
#, python-format
msgid "Could not find bucket with ID %(bucket_id)s"
msgstr "Could not find bucket with ID %(bucket_id)s"

#: glance/store/s3.py:503
#, python-format
msgid ""
"Failed to add bucket to S3.\n"
"Got error from S3: %(e)s"
msgstr ""
"Failed to add bucket to S3.\n"
"Got error from S3: %(e)s"

#: glance/store/s3.py:507
#, python-format
msgid ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."
msgstr ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."

#: glance/store/s3.py:526
#, python-format
msgid "Could not find key %(obj)s in bucket %(bucket)s"
msgstr "Could not find key %(obj)s in bucket %(bucket)s"

#: glance/store/scrubber.py:37
msgid ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."
msgstr ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."

#: glance/store/scrubber.py:42
msgid ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."
msgstr ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."

#: glance/store/scrubber.py:52
#, python-format
msgid "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"
msgstr "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"

#: glance/store/scrubber.py:65
msgid "Daemon Shutdown on KeyboardInterrupt"
msgstr "Daemon Shutdown on KeyboardInterrupt"

#: glance/store/scrubber.py:69
msgid "Running application"
msgstr "Running application"

#: glance/store/scrubber.py:72
#, python-format
msgid "Next run scheduled in %s seconds"
msgstr "Next run scheduled in %s seconds"

#: glance/store/scrubber.py:88
#, python-format
msgid "Initializing scrubber with conf: %s"
msgstr "Initializing scrubber with conf: %s"

#: glance/store/scrubber.py:104
#, python-format
msgid "%s does not exist"
msgstr "%s does not exist"

#: glance/store/scrubber.py:126 glance/store/scrubber.py:197
#, python-format
msgid "Deleting %s images"
msgstr "Deleting %s images"

#: glance/store/scrubber.py:139
#, python-format
msgid "Deleting %(uri)s"
msgstr "Deleting %(uri)s"

#: glance/store/scrubber.py:147
#, python-format
msgid "Failed to delete image from store (%(id)s)."
msgstr "Failed to delete image from store (%(id)s)."

#: glance/store/scrubber.py:151
#, python-format
msgid "Image not found in store (%(id)s)."
msgstr "Image not found in store (%(id)s)."

#: glance/store/scrubber.py:170
#, python-format
msgid "Getting images deleted before %s"
msgstr "Getting images deleted before %s"

#: glance/store/swift.py:51
msgid "Whether to use ServiceNET to communicate with the Swift storage servers."
msgstr "Whether to use ServiceNET to communicate with the Swift storage servers."

#: glance/store/swift.py:54
msgid "The address where the Swift authentication service is listening."
msgstr "The address where the Swift authentication service is listening."

#: glance/store/swift.py:57
msgid "The user to authenticate against the Swift authentication service"
msgstr "The user to authenticate against the Swift authentication service"

#: glance/store/swift.py:60
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service."
msgstr ""
"Auth key for the user authenticating against the Swift authentication "
"service."

#: glance/store/swift.py:63
msgid ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace"
msgstr ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace"

#: glance/store/swift.py:67
msgid ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."
msgstr ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."

#: glance/store/swift.py:71
msgid ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."
msgstr ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."

#: glance/store/swift.py:76
msgid ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."
msgstr ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."

#: glance/store/swift.py:81
msgid ""
"Container within the account that the account should use for storing "
"images in Swift."
msgstr ""
"Container within the account that the account should use for storing "
"images in Swift."

#: glance/store/swift.py:85
msgid ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift"
msgstr ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift"

#: glance/store/swift.py:89
msgid ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."
msgstr ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."

#: glance/store/swift.py:92
msgid ""
"A boolean value that determines if we create the container if it does not"
" exist."
msgstr ""
"A boolean value that determines if we create the container if it does not"
" exist."

#: glance/store/swift.py:95
msgid ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."
msgstr ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."

#: glance/store/swift.py:99
msgid ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."
msgstr ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."

#: glance/store/swift.py:169
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/store/swift.py:175
#, python-format
msgid "Invalid store URI: %(reason)s"
msgstr "Invalid store URI: %(reason)s"

#: glance/store/swift.py:219
msgid "Badly formed Swift URI."
msgstr "Badly formed Swift URI."

#: glance/store/swift.py:279 glance/store/swift.py:475
#: glance/store/swift.py:634
msgid "Swift could not find image at URI."
msgstr "Swift could not find image at URI."

#: glance/store/swift.py:317
#, python-format
msgid "Deleting chunk %s"
msgstr "Deleting chunk %s"

#: glance/store/swift.py:321
#, python-format
msgid "Failed to delete orphaned chunk %s/%s"
msgstr "Failed to delete orphaned chunk %s/%s"

#: glance/store/swift.py:331
#, python-format
msgid "Adding image object '%(obj_name)s' to Swift"
msgstr "Adding image object '%(obj_name)s' to Swift"

#: glance/store/swift.py:351
msgid "Cannot determine image size. Adding as a segmented object to Swift."
msgstr "Cannot determine image size. Adding as a segmented object to Swift."

#: glance/store/swift.py:385
#, python-format
msgid ""
"Wrote chunk %(chunk_name)s (%(chunk_id)d/%(total_chunks)s) of length "
"%(bytes_read)d to Swift returning MD5 of content: %(chunk_etag)s"
msgstr ""
"Wrote chunk %(chunk_name)s (%(chunk_id)d/%(total_chunks)s) of length "
"%(bytes_read)d to Swift returning MD5 of content: %(chunk_etag)s"

#: glance/store/swift.py:394
msgid "Deleting final zero-length chunk"
msgstr "Deleting final zero-length chunk"

#: glance/store/swift.py:431
msgid "Swift already has an image at this location"
msgstr "Swift already has an image at this location"

#: glance/store/swift.py:433
#, python-format
msgid ""
"Failed to add object to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""
"Failed to add object to Swift.\n"
"Got error from Swift: %(e)s"

#: glance/store/swift.py:496
#, python-format
msgid ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"

#: glance/store/swift.py:500
#, python-format
msgid ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."
msgstr ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."

#: glance/store/swift.py:544
msgid "Location is missing user:password information."
msgstr "Location is missing user:password information."

#: glance/store/swift.py:556
#, python-format
msgid "Badly formed tenant:user '%(user)s' in Swift URI"
msgstr "Badly formed tenant:user '%(user)s' in Swift URI"

#: glance/store/swift.py:582
msgid "Multi-tenant Swift storage requires a context."
msgstr "Multi-tenant Swift storage requires a context."

#: glance/store/swift.py:586
msgid "Multi-tenant Swift storage requires a service catalog."
msgstr "Multi-tenant Swift storage requires a service catalog."

#: glance/tests/unit/test_migrations.py:641
#, python-format
msgid "location: %s data lost"
msgstr "location: %s data lost"

