# English (United States) translations for glance.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-20 06:06+0000\n"
"PO-Revision-Date: 2013-04-10 10:09+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en_US <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/location.py:82
msgid "Invalid location"
msgstr ""

#: glance/location.py:293
msgid "Invalid locations"
msgstr ""

#: glance/location.py:299
#, python-format
msgid "Original locations is not empty: %s"
msgstr ""

#: glance/location.py:369 glance/common/exception.py:345
msgid "No image data could be found"
msgstr "No image data could be found"

#: glance/location.py:378
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr ""

#: glance/notifier.py:182
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr "An error occurred during image.send notification: %(err)s"

#: glance/notifier.py:199 glance/api/v1/upload_utils.py:196
#: glance/api/v2/image_data.py:114
#, python-format
msgid "Image storage media is full: %s"
msgstr "Image storage media is full: %s"

#: glance/notifier.py:204 glance/api/v1/upload_utils.py:205
#: glance/api/v2/image_data.py:138
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "Insufficient permissions on image storage media: %s"

#: glance/notifier.py:209
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:216
#, python-format
msgid "Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:223
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:229
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have "
"been deleted during the upload: %(error)s"
msgstr ""

#: glance/notifier.py:237
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""

#: glance/notifier.py:244
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error:"
" %(error)s"
msgstr ""

#: glance/schema.py:59
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr "custom properties (%(props)s) conflict with base properties"

#: glance/scrubber.py:44
msgid ""
"Directory that the scrubber will use to track information about what to "
"delete. Make sure this is set in glance-api.conf and glance-"
"scrubber.conf."
msgstr ""

#: glance/scrubber.py:49
msgid "The amount of time in seconds to delay before performing a delete."
msgstr "The amount of time in seconds to delay before performing a delete."

#: glance/scrubber.py:52
msgid ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."
msgstr ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."

#: glance/scrubber.py:57
msgid ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."
msgstr ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."

#: glance/scrubber.py:551
#, python-format
msgid "%s file is not exists."
msgstr ""

#: glance/scrubber.py:556
#, python-format
msgid "%s file contains conflicting cleanup timestamp."
msgstr ""

#: glance/api/authorization.py:129 glance/api/authorization.py:140
#, python-format
msgid "You cannot get image member for %s"
msgstr "You cannot get image member for %s"

#: glance/api/authorization.py:148
#, python-format
msgid "You cannot delete image member for %s"
msgstr "You cannot delete image member for %s"

#: glance/api/authorization.py:157
#, python-format
msgid "You cannot add image member for %s"
msgstr "You cannot add image member for %s"

#: glance/api/authorization.py:166
#, python-format
msgid "You cannot update image member %s"
msgstr "You cannot update image member %s"

#: glance/api/authorization.py:185
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "You are not permitted to create images owned by '%s'."

#: glance/api/authorization.py:203
msgid "You are not permitted to create image members for the image."
msgstr "You are not permitted to create image members for the image."

#: glance/api/authorization.py:208 glance/api/authorization.py:399
msgid "Public images do not have members."
msgstr "Public images do not have members."

#: glance/api/authorization.py:224
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr ""

#: glance/api/authorization.py:234
msgid "You are not permitted to modify locations for this image."
msgstr "You are not permitted to modify locations for this image."

#: glance/api/authorization.py:258
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "You are not permitted to modify '%s' on this image."

#: glance/api/authorization.py:262
msgid "You are not permitted to modify this image."
msgstr "You are not permitted to modify this image."

#: glance/api/authorization.py:275
msgid "You are not permitted to modify tags on this image."
msgstr "You are not permitted to modify tags on this image."

#: glance/api/authorization.py:316
msgid "You are not permitted to delete this image."
msgstr "You are not permitted to delete this image."

#: glance/api/authorization.py:327
msgid "You are not permitted to upload data for this image."
msgstr "You are not permitted to upload data for this image."

#: glance/api/authorization.py:364 glance/api/authorization.py:368
#: glance/api/authorization.py:372
msgid "You are not permitted to set status on this task."
msgstr ""

#: glance/api/authorization.py:431
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr ""

#: glance/api/common.py:64
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "Corrupt image download for image %(image_id)s"

#: glance/api/policy.py:34
msgid "The location of the policy file."
msgstr "The location of the policy file."

#: glance/api/policy.py:36
msgid "The default policy to use."
msgstr "The default policy to use."

#: glance/api/policy.py:96
msgid "Unable to find policy file"
msgstr "Unable to find policy file"

#: glance/api/policy.py:220 glance/quota/__init__.py:354
#, python-format
msgid "Invalid locations: %s"
msgstr ""

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr "Role used to identify an authenticated user as administrator."

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr "Unable to retrieve request id from context"

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr "Invalid service catalog json."

#: glance/api/middleware/version_negotiation.py:41
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr "Determining version of request: %(method)s %(path)s Accept: %(accept)s"

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr "Store for image_id not found: %s"

#: glance/api/v1/images.py:79
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:84
#, python-format
msgid "Invalid container format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:89
#, python-format
msgid "Image name too long: %d"
msgstr "Image name too long: %d"

#: glance/api/v1/images.py:100
msgid ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."
msgstr ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."

#: glance/api/v1/images.py:178
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""

#: glance/api/v1/images.py:341
msgid "This operation is currently not permitted on Glance images details."
msgstr ""

#: glance/api/v1/images.py:392
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr ""

#: glance/api/v1/images.py:548
#, python-format
msgid "Failed to reserve image. Got error: %s"
msgstr ""

#: glance/api/v1/images.py:848
msgid "Forbidden to update deleted image."
msgstr "Forbidden to update deleted image."

#: glance/api/v1/images.py:859
#, python-format
msgid "Forbidden to modify '%s' of active image."
msgstr ""

#: glance/api/v1/images.py:877
msgid "Cannot upload to an unqueued image"
msgstr "Cannot upload to an unqueued image"

#: glance/api/v1/images.py:901
msgid "Attempted to update Location field for an image not in queued status."
msgstr "Attempted to update Location field for an image not in queued status."

#: glance/api/v1/images.py:948
#, python-format
msgid "Failed to find image to update: %s"
msgstr ""

#: glance/api/v1/images.py:956
#, python-format
msgid "Forbidden to update image: %s"
msgstr ""

#: glance/api/v1/images.py:1042
#, python-format
msgid "Failed to find image to delete: %s"
msgstr ""

#: glance/api/v1/images.py:1050
#, python-format
msgid "Forbidden to delete image: %s"
msgstr ""

#: glance/api/v1/images.py:1113 glance/api/v1/upload_utils.py:215
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "Denying attempt to upload image larger than %d bytes."

#: glance/api/v1/members.py:40 glance/registry/api/v1/members.py:34
msgid "No authenticated user"
msgstr "No authenticated user"

#: glance/api/v1/members.py:52
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr ""

#: glance/api/v1/members.py:116 glance/common/exception.py:295
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for "
"this image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/api/v1/upload_utils.py:126
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."

#: glance/api/v1/upload_utils.py:225
#, python-format
msgid "Denying attempt to upload image because it exceeds the .quota: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:254
#, python-format
msgid "Failed to upload image %s"
msgstr ""

#: glance/api/v2/image_data.py:76
#, python-format
msgid ""
"Image %(id)s could not be found after upload.The image may have been "
"deleted during the upload: %(error)s Cleaning up the chunks uploaded"
msgstr ""

#: glance/api/v2/image_data.py:122
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr ""

#: glance/api/v2/image_data.py:130
#, python-format
msgid "The incoming image is too large: %s"
msgstr ""

#: glance/api/v2/image_members.py:191 glance/api/v2/images.py:294
msgid "Body expected in request."
msgstr "Body expected in request."

#: glance/api/v2/image_members.py:202
msgid "Member to be added not specified"
msgstr "Member to be added not specified"

#: glance/api/v2/image_members.py:205
msgid "Member can't be empty"
msgstr ""

#: glance/api/v2/image_members.py:214
msgid "Status not specified"
msgstr "Status not specified"

#: glance/api/v2/image_members.py:269
msgid "An identifier for the image member (tenantId)"
msgstr "An identifier for the image member (tenantId)"

#: glance/api/v2/image_members.py:273 glance/api/v2/images.py:668
msgid "An identifier for the image"
msgstr "An identifier for the image"

#: glance/api/v2/image_members.py:279
msgid "Date and time of image member creation"
msgstr "Date and time of image member creation"

#: glance/api/v2/image_members.py:286
msgid "Date and time of last modification of image member"
msgstr "Date and time of last modification of image member"

#: glance/api/v2/image_members.py:291
msgid "The status of this image member"
msgstr "The status of this image member"

#: glance/api/v2/images.py:160 glance/api/v2/images.py:188
#, python-format
msgid "Property %s does not exist."
msgstr "Property %s does not exist."

#: glance/api/v2/images.py:172
#, python-format
msgid "Property %s already present."
msgstr "Property %s already present."

#: glance/api/v2/images.py:183
#, python-format
msgid "Property %s may not be removed."
msgstr "Property %s may not be removed."

#: glance/api/v2/images.py:201
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr ""

#: glance/api/v2/images.py:220
msgid "Cannot replace locations from a non-empty list to a non-empty list."
msgstr ""

#: glance/api/v2/images.py:244
msgid "Invalid position for adding a location."
msgstr ""

#: glance/api/v2/images.py:260
msgid "Invalid position for removing a location."
msgstr ""

#: glance/api/v2/images.py:302 glance/api/v2/images.py:402
#, python-format
msgid "Attribute '%s' is read-only."
msgstr ""

#: glance/api/v2/images.py:327 glance/api/v2/images.py:349
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "Unable to find '%s' in JSON Schema change"

#: glance/api/v2/images.py:335
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."
msgstr ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."

#: glance/api/v2/images.py:340
msgid ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."
msgstr ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."

#: glance/api/v2/images.py:377
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "Pointer `%s` does not start with \"/\"."

#: glance/api/v2/images.py:380
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: glance/api/v2/images.py:383
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: glance/api/v2/images.py:386
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: glance/api/v2/images.py:389
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr "Pointer `%s` contains \"~\" not part of a recognized escape sequence."

#: glance/api/v2/images.py:395
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "Operation \"%s\" requires a member named \"value\"."

#: glance/api/v2/images.py:405
#, python-format
msgid "Attribute '%s' is reserved."
msgstr ""

#: glance/api/v2/images.py:435
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr ""

#: glance/api/v2/images.py:447
msgid "Unrecognized JSON Schema draft version"
msgstr "Unrecognized JSON Schema draft version"

#: glance/api/v2/images.py:468
msgid "Request body must be a JSON array of operation objects."
msgstr "Request body must be a JSON array of operation objects."

#: glance/api/v2/images.py:473
msgid "Operations must be JSON objects."
msgstr "Operations must be JSON objects."

#: glance/api/v2/images.py:495 glance/api/v2/tasks.py:169
#: glance/registry/api/v1/images.py:265
msgid "limit param must be an integer"
msgstr "limit param must be an integer"

#: glance/api/v2/images.py:499 glance/api/v2/tasks.py:173
#: glance/registry/api/v1/images.py:268
msgid "limit param must be positive"
msgstr "limit param must be positive"

#: glance/api/v2/images.py:506 glance/api/v2/tasks.py:139
#, python-format
msgid "Invalid sort direction: %s"
msgstr "Invalid sort direction: %s"

#: glance/api/v2/images.py:513
#, python-format
msgid "Invalid status: %s"
msgstr "Invalid status: %s"

#: glance/api/v2/images.py:522
#, python-format
msgid "Invalid visibility value: %s"
msgstr "Invalid visibility value: %s"

#: glance/api/v2/images.py:526
msgid "The \"changes-since\" filter is no longer available on v2."
msgstr ""

#: glance/api/v2/images.py:674
msgid "Descriptive name for the image"
msgstr "Descriptive name for the image"

#: glance/api/v2/images.py:679
msgid "Status of the image (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:685
msgid "Scope of image accessibility"
msgstr "Scope of image accessibility"

#: glance/api/v2/images.py:690
msgid "If true, image will not be deletable."
msgstr "If true, image will not be deletable."

#: glance/api/v2/images.py:694
msgid "md5 hash of image contents. (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:699
msgid "Owner of the image"
msgstr ""

#: glance/api/v2/images.py:704
msgid "Size of image file in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:708
msgid "Virtual size of image in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:712
msgid "Format of the container"
msgstr ""

#: glance/api/v2/images.py:717
msgid "Format of the disk"
msgstr ""

#: glance/api/v2/images.py:722
msgid "Date and time of image registration (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:730
msgid "Date and time of the last image modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:736
msgid "List of strings related to the image"
msgstr "List of strings related to the image"

#: glance/api/v2/images.py:744
msgid "URL to access the image file kept in external store (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:749
msgid "Amount of ram (in MB) required to boot image."
msgstr "Amount of ram (in MB) required to boot image."

#: glance/api/v2/images.py:753
msgid "Amount of disk space (in GB) required to boot image."
msgstr "Amount of disk space (in GB) required to boot image."

#: glance/api/v2/images.py:783
msgid "A set of URLs to access the image file kept in external store"
msgstr ""

#: glance/api/v2/tasks.py:119
msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""

#: glance/api/v2/tasks.py:133
msgid "Body expected in request"
msgstr ""

#: glance/api/v2/tasks.py:148
#, python-format
msgid "Invalid status value: %s"
msgstr ""

#: glance/api/v2/tasks.py:154
#, python-format
msgid "Invalid type value: %s"
msgstr ""

#: glance/api/v2/tasks.py:161 glance/registry/api/v1/images.py:277
msgid "Invalid marker format"
msgstr "Invalid marker format"

#: glance/api/v2/tasks.py:182
#, python-format
msgid "Task '%s' is required"
msgstr ""

#: glance/api/v2/tasks.py:305
msgid "An identifier for the task"
msgstr ""

#: glance/api/v2/tasks.py:306
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0"
"-9a-fA-F]){12}$"
msgstr ""

#: glance/api/v2/tasks.py:311
msgid "The type of task represented by this content"
msgstr ""

#: glance/api/v2/tasks.py:318
msgid "The current status of this task"
msgstr ""

#: glance/api/v2/tasks.py:328
msgid "The parameters required by task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:332
msgid "The result of current task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:336
msgid "An identifier for the owner of this task"
msgstr ""

#: glance/api/v2/tasks.py:340
msgid ""
"Human-readable informative message only included when appropriate "
"(usually on failure)"
msgstr ""

#: glance/api/v2/tasks.py:345
msgid "Datetime when this resource would be subject to removal"
msgstr ""

#: glance/api/v2/tasks.py:350
msgid "Datetime when this resource was created"
msgstr ""

#: glance/api/v2/tasks.py:354
msgid "Datetime when this resource was updated"
msgstr ""

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr ""

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr ""

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr ""

#: glance/cmd/control.py:160
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr ""

#: glance/cmd/control.py:175
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr ""

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr ""

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr ""

#: glance/cmd/control.py:225
#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr ""

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr ""

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr ""

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr ""

#: glance/cmd/control.py:346
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr ""

#: glance/cmd/manage.py:60
msgid ""
"DEPRECATED. TO BE REMOVED IN THE JUNO RELEASE. Whether or not to enforce "
"that all DB tables have charset utf8. If your database tables do not have"
" charset utf8 you will need to convert before this option is removed. "
"This option is only relevant if your database engine is MySQL."
msgstr ""

#: glance/cmd/replicator.py:58
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did "
"not find it. This indicates that we do not have permissions to see all "
"the images on the slave server."
msgstr ""

#: glance/cmd/replicator.py:283 glance/cmd/replicator.py:315
#: glance/cmd/replicator.py:387 glance/cmd/replicator.py:463
#: glance/cmd/replicator.py:534
msgid "Too few arguments."
msgstr ""

#: glance/cmd/replicator.py:299
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr ""

#: glance/cmd/replicator.py:683
#, python-format
msgid "Unknown command: %s"
msgstr ""

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr "Unexpected response: %s"

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "Unknown auth strategy '%s'"

#: glance/common/auth.py:275
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr "Encountered service with no \"type\": %s"

#: glance/common/client.py:242
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"

#: glance/common/client.py:250
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"

#: glance/common/client.py:259
#, python-format
msgid "The key file you specified %s does not exist"
msgstr "The key file you specified %s does not exist"

#: glance/common/client.py:266
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "The cert file you specified %s does not exist"

#: glance/common/client.py:273
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "The CA file you specified %s does not exist"

#: glance/common/client.py:412
#, python-format
msgid "Constructed URL: %s"
msgstr "Constructed URL: %s"

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr "Name of the paste configuration file."

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance/common/config.py:60
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"

#: glance/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values "
"evaluate to unlimited."
msgstr ""

#: glance/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate"
" to unlimited."
msgstr ""

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr "Python module path of data access API"

#: glance/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"

#: glance/common/config.py:87
msgid "Maximum permissible number of items that could be returned by a request"
msgstr "Maximum permissible number of items that could be returned by a request"

#: glance/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""

#: glance/common/config.py:95
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance/common/config.py:100
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."

#: glance/common/config.py:103
msgid ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited.Optional unit can be specified for the value. Accepted units "
"are B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, "
"GigaBytes and TeraBytesrespectively. If no unit is specified then Bytes "
"is assumed. Note that there should not be any space between value and "
"unit and units are case sensitive."
msgstr ""

#: glance/common/config.py:113
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance/common/config.py:115
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance/common/config.py:117
msgid "Deploy the v1 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:119
msgid "Deploy the v2 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:121
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr "The hostname/IP of the pydev process listening for debug connections"

#: glance/common/config.py:124
msgid "The port on which a pydev process is listening for connections."
msgstr "The port on which a pydev process is listening for connections."

#: glance/common/config.py:127
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."

#: glance/common/config.py:185
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr ""

#: glance/common/config.py:224
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr "An unknown exception occurred"

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "Missing required credential: %(required)s"

#: glance/common/exception.py:67
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr "An object with the specified identifier was not found."

#: glance/common/exception.py:76
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr "Unknown scheme '%(scheme)s' found in URI"

#: glance/common/exception.py:80
msgid "The Store URI was malformed."
msgstr "The Store URI was malformed."

#: glance/common/exception.py:84
msgid "An object with the same identifier already exists."
msgstr "An object with the same identifier already exists."

#: glance/common/exception.py:88
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance/common/exception.py:93
msgid "There is not enough disk space on the image storage media."
msgstr "There is not enough disk space on the image storage media."

#: glance/common/exception.py:97
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""

#: glance/common/exception.py:102
msgid "Permission to write image storage media denied."
msgstr "Permission to write image storage media denied."

#: glance/common/exception.py:106
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "Connect error/bad request to Auth service at URL %(url)s."

#: glance/common/exception.py:110
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "Auth service at URL %(url)s not found."

#: glance/common/exception.py:114
msgid "Authorization failed."
msgstr "Authorization failed."

#: glance/common/exception.py:118
msgid "You are not authenticated."
msgstr "You are not authenticated."

#: glance/common/exception.py:122 glance/common/exception.py:126
msgid "You are not authorized to complete this action."
msgstr "You are not authorized to complete this action."

#: glance/common/exception.py:130
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "Image %(image_id)s is protected and cannot be deleted."

#: glance/common/exception.py:134
msgid "Data supplied was not valid."
msgstr "Data supplied was not valid."

#: glance/common/exception.py:138
msgid "Sort key supplied was not valid."
msgstr "Sort key supplied was not valid."

#: glance/common/exception.py:142
msgid "Invalid configuration in property protection file."
msgstr ""

#: glance/common/exception.py:146
msgid "Invalid configuration in glance-swift conf file."
msgstr ""

#: glance/common/exception.py:150
msgid "Unable to filter using the specified range."
msgstr "Unable to filter using the specified range."

#: glance/common/exception.py:154
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "Attribute '%(property)s' is read-only."

#: glance/common/exception.py:158
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "Attribute '%(property)s' is reserved."

#: glance/common/exception.py:162
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "Redirecting to %(uri)s for authorization."

#: glance/common/exception.py:166
msgid "There was an error connecting to a server"
msgstr "There was an error connecting to a server"

#: glance/common/exception.py:170
msgid "There was an error configuring the client."
msgstr "There was an error configuring the client."

#: glance/common/exception.py:174
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"

#: glance/common/exception.py:180
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:191
msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: glance/common/exception.py:202
msgid "The request returned 500 Internal Server Error."
msgstr "The request returned 500 Internal Server Error."

#: glance/common/exception.py:206
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:211
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "Invalid content type %(content_type)s"

#: glance/common/exception.py:215
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr "Registry was not configured correctly on API server. Reason: %(reason)s"

#: glance/common/exception.py:220
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"

#: glance/common/exception.py:225
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"

#: glance/common/exception.py:230
msgid "Deleting images from this store is not supported."
msgstr "Deleting images from this store is not supported."

#: glance/common/exception.py:234
msgid "Getting images from this store is not supported."
msgstr ""

#: glance/common/exception.py:238
msgid "Adding images to this store is not supported."
msgstr ""

#: glance/common/exception.py:242
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr "Configuration for store failed. Adding images to this store is disabled."

#: glance/common/exception.py:247
msgid "Store is not configured."
msgstr ""

#: glance/common/exception.py:251
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "Maximum redirects (%(redirects)s) was exceeded."

#: glance/common/exception.py:255
msgid "Received invalid HTTP redirect."
msgstr "Received invalid HTTP redirect."

#: glance/common/exception.py:259
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Response from Keystone does not contain a Glance endpoint."

#: glance/common/exception.py:263
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."

#: glance/common/exception.py:269
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "Server worker creation failed: %(reason)s."

#: glance/common/exception.py:273
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "Unable to load schema: %(reason)s"

#: glance/common/exception.py:277
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "Provided object does not match schema '%(schema)s': %(reason)s"

#: glance/common/exception.py:282
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr "Provided header feature is unsupported: %(feature)s"

#: glance/common/exception.py:286
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."

#: glance/common/exception.py:291
msgid "The provided image is too large."
msgstr "The provided image is too large."

#: glance/common/exception.py:301
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:306
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:311
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:316
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""

#: glance/common/exception.py:320
msgid "An unknown task exception occurred"
msgstr ""

#: glance/common/exception.py:324
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr ""

#: glance/common/exception.py:328
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr ""

#: glance/common/exception.py:332
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr ""

#: glance/common/exception.py:336
#, python-format
msgid "Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""

#: glance/common/exception.py:341
#, python-format
msgid "The location %(location)s already exists"
msgstr ""

#: glance/common/exception.py:349
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance/common/exception.py:354
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not "
"allowed"
msgstr ""

#: glance/common/property_utils.py:36
msgid "The location of the property protection file."
msgstr ""

#: glance/common/property_utils.py:39
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in"
" the property protection file."
msgstr ""

#: glance/common/property_utils.py:74
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:81
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:100
#, python-format
msgid ""
"Multiple policies '%s' not allowedfor a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:113
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and"
" '!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:126
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""

#: glance/common/property_utils.py:138
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:140
msgid "Request must be a list of commands"
msgstr ""

#: glance/common/rpc.py:145
#, python-format
msgid "Bad Command: %s"
msgstr ""

#: glance/common/rpc.py:152
#, python-format
msgid "Wrong command structure: %s"
msgstr ""

#: glance/common/rpc.py:161
msgid "Command not found"
msgstr ""

#: glance/common/rpc.py:183
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/store_utils.py:34 glance/registry/client/__init__.py:43
msgid ""
"Whether to pass through the user token when making requests to the "
"registry."
msgstr ""

#: glance/common/swift_store_utils.py:29
msgid ""
"The reference to the default swift account/backing store parameters to "
"use for adding new images."
msgstr ""

#: glance/common/swift_store_utils.py:32
msgid ""
"The address where the Swift authentication service is "
"listening.(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:35
msgid ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:38
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:41
msgid "The config file that has the swift account(s)configs."
msgstr ""

#: glance/common/swift_store_utils.py:83
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:97
msgid "Invalid format of swift store configcfg"
msgstr ""

#: glance/common/utils.py:111
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr "Error: cooperative_iter exception %s"

#: glance/common/utils.py:243
#, python-format
msgid "Bad header: %(header_name)s"
msgstr ""

#: glance/common/utils.py:253
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr ""

#: glance/common/utils.py:260
#, python-format
msgid "Image %(key)s must be >= 0 ('%(value)s' specified)."
msgstr ""

#: glance/common/utils.py:433
msgid ""
"Error setting up the debug environment.  Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by "
"pydev_worker_debug_port."
msgstr ""

#: glance/common/utils.py:470
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: glance/common/utils.py:503
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it.  Error: %(ioe)s"
msgstr ""

#: glance/common/utils.py:510
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it. OpenSSL error: %(ce)s"
msgstr ""

#: glance/common/utils.py:524
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""

#: glance/common/utils.py:602
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:605
#, python-format
msgid "Port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:614
#, python-format
msgid "Host \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:617
#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in "
"brackets separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""

#: glance/common/wsgi.py:55
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."

#: glance/common/wsgi.py:58
msgid "The port on which the server will listen."
msgstr "The port on which the server will listen."

#: glance/common/wsgi.py:63
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr "The backlog value that will be used when creating the TCP listener socket."

#: glance/common/wsgi.py:66
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in "
"seconds that the connection must be idle before TCP starts sending "
"keepalive probes."
msgstr ""

#: glance/common/wsgi.py:69
msgid "CA certificate file to use to verify connecting clients."
msgstr "CA certificate file to use to verify connecting clients."

#: glance/common/wsgi.py:71
msgid "Certificate file to use when starting API server securely."
msgstr "Certificate file to use when starting API server securely."

#: glance/common/wsgi.py:73
msgid "Private key file to use when starting API server securely."
msgstr "Private key file to use when starting API server securely."

#: glance/common/wsgi.py:79
msgid ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."
msgstr ""

#: glance/common/wsgi.py:83
msgid ""
"Name of eventlet hub to use. Traditionally, we have only supported "
"'poll', however 'selects' may be appropriate for some platforms. See "
"http://eventlet.net/doc/hubs.html for more details."
msgstr ""

#: glance/common/wsgi.py:88
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated "
"by the Keystone v3 API with big service catalogs"
msgstr ""

#: glance/common/wsgi.py:96
msgid "If False fully disable profiling feature."
msgstr ""

#: glance/common/wsgi.py:98
msgid "If False doesn't trace SQL requests."
msgstr ""

#: glance/common/wsgi.py:142
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"

#: glance/common/wsgi.py:180
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: glance/common/wsgi.py:200
#, python-format
msgid "eventlet '%s' hub is not available on this platform"
msgstr ""

#: glance/common/wsgi.py:264
#, python-format
msgid "Starting %d workers"
msgstr "Starting %d workers"

#: glance/common/wsgi.py:279
#, python-format
msgid "Removing dead child %s"
msgstr "Removing dead child %s"

#: glance/common/wsgi.py:282
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr "Not respawning child %d, cannot recover from termination"

#: glance/common/wsgi.py:286
msgid "All workers have terminated. Exiting"
msgstr "All workers have terminated. Exiting"

#: glance/common/wsgi.py:294
msgid "Caught keyboard interrupt. Exiting."
msgstr "Caught keyboard interrupt. Exiting."

#: glance/common/wsgi.py:320
#, python-format
msgid "Child %d exiting normally"
msgstr "Child %d exiting normally"

#: glance/common/wsgi.py:325
#, python-format
msgid "Started child %s"
msgstr "Started child %s"

#: glance/common/wsgi.py:349
msgid "Starting single process server"
msgstr "Starting single process server"

#: glance/common/wsgi.py:566
msgid "Malformed JSON in request body."
msgstr "Malformed JSON in request body."

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image "
"location order. Currently two strategies are packaged with Glance "
"'location_order' and 'store_type'."
msgstr ""

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being "
"used."
msgstr ""

#: glance/common/location_strategy/__init__.py:61
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:76
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""

#: glance/common/location_strategy/store_type.py:25
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'known_stores' config "
"option. This option will be applied when you using 'store_type' option as"
" image location strategy defined by the 'location_strategy' config "
"option."
msgstr ""

#: glance/db/__init__.py:68 glance/db/__init__.py:175 glance/db/__init__.py:187
#, python-format
msgid "No image found with ID %s"
msgstr ""

#: glance/db/__init__.py:246
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""

#: glance/db/__init__.py:263
#, python-format
msgid "The specified member %s could not be found"
msgstr ""

#: glance/db/__init__.py:341 glance/db/__init__.py:362
#: glance/db/__init__.py:379 glance/db/simple/api.py:849
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:43
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"

#: glance/db/simple/api.py:48
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr "Returning %(funcname)s: %(output)s"

#: glance/db/simple/api.py:261 glance/db/sqlalchemy/api.py:446
msgid "Unable to filter on a range with a non-numeric value."
msgstr "Unable to filter on a range with a non-numeric value."

#: glance/db/simple/api.py:332
#, python-format
msgid "Could not find image %s"
msgstr "Could not find image %s"

#: glance/db/simple/api.py:336
msgid "Unable to get deleted image"
msgstr "Unable to get deleted image"

#: glance/db/simple/api.py:340
msgid "Unable to get unowned image"
msgstr "Unable to get unowned image"

#: glance/db/simple/api.py:432 glance/db/sqlalchemy/api.py:1086
msgid "Image id is required."
msgstr ""

#: glance/db/simple/api.py:490 glance/db/sqlalchemy/api.py:783
#, python-format
msgid "The location data has an invalid ID: %d"
msgstr ""

#: glance/db/simple/api.py:510 glance/db/simple/api.py:536
#: glance/db/sqlalchemy/api.py:805 glance/db/sqlalchemy/api.py:833
#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr ""

#: glance/db/simple/api.py:520
msgid ""
"The status of deleted image location can only be set to 'pending_delete' "
"or 'deleted'."
msgstr ""

#: glance/db/simple/api.py:854
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:977
msgid "Task does not exist"
msgstr ""

#: glance/db/simple/api.py:1015
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:106
msgid "You do not own this image"
msgstr "You do not own this image"

#: glance/db/sqlalchemy/api.py:376
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Unknown sort direction, must be 'desc' or 'asc'"

#: glance/db/sqlalchemy/api.py:734
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""

#: glance/db/sqlalchemy/api.py:814
msgid ""
"The status of deleted image location can only be set to 'pending_delete' "
"or 'deleted'"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:90
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:156
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:127
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:192
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr "Badly formed credentials '%(creds)s' in Swift URI"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:139
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:204
#: glance/store/swift.py:251
msgid "Badly formed credentials in Swift URI."
msgstr "Badly formed credentials in Swift URI."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:156
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:221
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr ""

#: glance/domain/__init__.py:60
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr ""

#: glance/domain/__init__.py:130
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr ""

#: glance/domain/__init__.py:152
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "Property %s must be set prior to saving data."

#: glance/domain/__init__.py:155
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "Properties %s must be set prior to saving data."

#: glance/domain/__init__.py:172
msgid "Visibility must be either \"public\" or \"private\""
msgstr ""

#: glance/domain/__init__.py:191
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:203
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:215 glance/domain/__init__.py:228
msgid "Cannot be a negative value"
msgstr ""

#: glance/domain/__init__.py:293
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "Status must be \"pending\", \"accepted\" or \"rejected\"."

#: glance/domain/__init__.py:369
#, python-format
msgid "Task [%(task_id)s] status changing from %(cur_status)s to %(new_status)s"
msgstr ""

#: glance/domain/__init__.py:375
#, python-format
msgid ""
"Task [%(task_id)s] status failed to change from %(cur_status)s to "
"%(new_status)s"
msgstr ""

#: glance/image_cache/__init__.py:39
msgid "The driver to use for image cache management."
msgstr "The driver to use for image cache management."

#: glance/image_cache/__init__.py:41
msgid "The maximum size in bytes that the cache can use."
msgstr "The maximum size in bytes that the cache can use."

#: glance/image_cache/__init__.py:43
msgid ""
"The amount of time to let an image remain in the cache without being "
"accessed."
msgstr ""

#: glance/image_cache/__init__.py:46
msgid "Base directory that the Image Cache uses."
msgstr "Base directory that the Image Cache uses."

#: glance/image_cache/__init__.py:258
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr "Checksum verification failed. Aborted caching of image '%s'."

#: glance/image_cache/client.py:117
msgid ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"keystone authentication strategy is enabled\n"
msgstr ""

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr "Failed to read %s from config"

#: glance/image_cache/drivers/sqlite.py:44
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""
"The path to the sqlite file database that will be used for image cache "
"management."

#: glance/image_cache/drivers/sqlite.py:126
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr "Failed to initialize the image cache database. Got error: %s"

#: glance/openstack/common/gettextutils.py:320
msgid "Message objects do not support addition."
msgstr ""

#: glance/openstack/common/gettextutils.py:330
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: glance/openstack/common/lockutils.py:102
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: glance/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecated: %s"

#: glance/openstack/common/log.py:436
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: glance/openstack/common/log.py:486
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog facility must be one of: %s"

#: glance/openstack/common/log.py:729
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatal call to deprecated config: %(msg)s"

#: glance/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr "Failed to understand rule %(rule)s"

#: glance/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: glance/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr "Failed to understand rule %(rule)r"

#: glance/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: glance/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: glance/openstack/common/processutils.py:144
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: glance/openstack/common/processutils.py:150
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: glance/openstack/common/processutils.py:247
msgid "Environment not supported over SSH"
msgstr ""

#: glance/openstack/common/processutils.py:251
msgid "process_input not supported over SSH"
msgstr ""

#: glance/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: glance/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: glance/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr "Address to find the registry server."

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr "Port the registry server is listening on."

#: glance/registry/api/v1/images.py:126 glance/registry/api/v1/images.py:131
msgid "Invalid marker. Image could not be found."
msgstr "Invalid marker. Image could not be found."

#: glance/registry/api/v1/images.py:235
msgid "Unrecognized changes-since value"
msgstr "Unrecognized changes-since value"

#: glance/registry/api/v1/images.py:240
msgid "protected must be True, or False"
msgstr "protected must be True, or False"

#: glance/registry/api/v1/images.py:287
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "Unsupported sort_key. Acceptable values: %s"

#: glance/registry/api/v1/images.py:296
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "Unsupported sort_dir. Acceptable values: %s"

#: glance/registry/api/v1/images.py:322
msgid "is_public must be None, True, or False"
msgstr "is_public must be None, True, or False"

#: glance/registry/api/v1/images.py:416
msgid "Invalid image id format"
msgstr "Invalid image id format"

#: glance/registry/api/v1/images.py:431
#, python-format
msgid "Image with identifier %s already exists!"
msgstr "Image with identifier %s already exists!"

#: glance/registry/api/v1/images.py:435
#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr ""

#: glance/registry/api/v1/images.py:484
#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr ""

#: glance/registry/api/v1/members.py:103
#, python-format
msgid "Image %(id)s not found"
msgstr "Image %(id)s not found"

#: glance/registry/api/v1/members.py:119 glance/registry/api/v1/members.py:237
#: glance/registry/api/v1/members.py:301
msgid "No permission to share that image"
msgstr "No permission to share that image"

#: glance/registry/api/v1/members.py:130 glance/registry/api/v1/members.py:147
#: glance/registry/api/v1/members.py:250
#, python-format
msgid "Invalid membership association: %s"
msgstr "Invalid membership association: %s"

#: glance/registry/api/v1/members.py:314 glance/registry/api/v1/members.py:332
msgid "Membership could not be found."
msgstr "Membership could not be found."

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr ""

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either "
"http or https."
msgstr ""
"The protocol to use for communication with the registry server.  Either "
"http or https."

#: glance/registry/client/__init__.py:23
msgid "The path to the key file to use in SSL connections to the registry server."
msgstr "The path to the key file to use in SSL connections to the registry server."

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the cert file to use in SSL connections to the registry "
"server."
msgstr ""
"The path to the cert file to use in SSL connections to the registry "
"server."

#: glance/registry/client/__init__.py:29
msgid ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."
msgstr ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."

#: glance/registry/client/__init__.py:32
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."
msgstr ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."
msgstr ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."

#: glance/registry/client/__init__.py:46
msgid "The administrators user name."
msgstr "The administrators user name."

#: glance/registry/client/__init__.py:48
msgid "The administrators password."
msgstr "The administrators password."

#: glance/registry/client/__init__.py:50
msgid "The tenant name of the administrative user."
msgstr ""

#: glance/registry/client/__init__.py:52
msgid "The URL to the keystone service."
msgstr "The URL to the keystone service."

#: glance/registry/client/__init__.py:54
msgid "The strategy to use for authentication."
msgstr "The strategy to use for authentication."

#: glance/registry/client/__init__.py:56
msgid "The region for the authentication service."
msgstr "The region for the authentication service."

#: glance/registry/client/v1/api.py:33
msgid ""
"Whether to pass through headers containing user and tenant information "
"when making requests to the registry. This allows the registry to use the"
" context middleware without keystonemiddleware's auth_token middleware, "
"removing calls to the keystone auth service. It is recommended that when "
"using this option, secure communication between glance api and glance "
"registry is ensured by means other than auth_token middleware."
msgstr ""

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr "Configuration option was not valid"

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr "Could not find required configuration option"

#: glance/store/__init__.py:36
msgid ""
"List of which store classes and store class locations are currently known"
" to glance at startup."
msgstr ""
"List of which store classes and store class locations are currently known"
" to glance at startup."

#: glance/store/__init__.py:39
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."
msgstr ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."

#: glance/store/__init__.py:43
msgid "Turn on/off delayed delete."
msgstr "Turn on/off delayed delete."

#: glance/store/__init__.py:177
#, python-format
msgid "%s Skipping store driver."
msgstr ""

#: glance/store/__init__.py:183
#, python-format
msgid ""
"%s not found in `known_store`. Stores need to be explicitly enabled in "
"the configuration file."
msgstr ""

#: glance/store/__init__.py:219
#, python-format
msgid "Store for scheme %s not found"
msgstr "Store for scheme %s not found"

#: glance/store/__init__.py:319
#, python-format
msgid ""
"The image metadata key %(key)s has an invalid type of %(val)s.  Only "
"dict, list, and unicode are supported."
msgstr ""

#: glance/store/__init__.py:343
#, python-format
msgid ""
"The storage driver %(store)s returned invalid metadata %(metadata)s. This"
" must be a dictionary type"
msgstr ""

#: glance/store/__init__.py:352
#, python-format
msgid ""
"A bad metadata structure was returned from the %(store)s storage driver: "
"%(metadata)s.  %(error)s."
msgstr ""

#: glance/store/base.py:58
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr "Failed to configure store correctly: %s Disabling add method."

#: glance/store/cinder.py:115
msgid "URI must start with 'cinder://'"
msgstr ""

#: glance/store/cinder.py:123
msgid "URI contains invalid volume ID"
msgstr ""

#: glance/store/cinder.py:146
msgid "Cinder storage requires a context."
msgstr ""

#: glance/store/cinder.py:150
msgid "Cinder storage requires a service catalog."
msgstr ""

#: glance/store/cinder.py:172
#, python-format
msgid "Failed to get image size due to volume can not be found: %s"
msgstr ""

#: glance/store/cinder.py:177
#, python-format
msgid "Failed to get image size due to internal error: %s"
msgstr ""

#: glance/store/filesystem.py:42
msgid "Directory to which the Filesystem backend store writes images."
msgstr "Directory to which the Filesystem backend store writes images."

#: glance/store/filesystem.py:45
msgid ""
"List of directories and its priorities to which the Filesystem backend "
"store writes images."
msgstr ""

#: glance/store/filesystem.py:48
msgid ""
"The path to a file which contains the metadata to be returned with any "
"location associated with this store.  The file must contain a valid JSON "
"dict."
msgstr ""

#: glance/store/filesystem.py:79
msgid "No path specified in URI"
msgstr ""

#: glance/store/filesystem.py:133
#, python-format
msgid "Permission to write in %s denied"
msgstr ""

#: glance/store/filesystem.py:150
#, python-format
msgid "Directory to write image files does not exist (%s). Creating."
msgstr "Directory to write image files does not exist (%s). Creating."

#: glance/store/filesystem.py:164
#, python-format
msgid "Unable to create datadir: %s"
msgstr "Unable to create datadir: %s"

#: glance/store/filesystem.py:178
msgid ""
"Specify at least 'filesystem_store_datadir' or "
"'filesystem_store_datadirs' option"
msgstr ""

#: glance/store/filesystem.py:185
msgid ""
"Specify either 'filesystem_store_datadir' or 'filesystem_store_datadirs' "
"option"
msgstr ""

#: glance/store/filesystem.py:222
#, python-format
msgid ""
"Directory %(datadir_path)s specified multiple times in "
"filesystem_store_datadirs option of filesystem configuration"
msgstr ""

#: glance/store/filesystem.py:247
#, python-format
msgid "Invalid priority value %(priority)s in filesystem configuration"
msgstr ""

#: glance/store/filesystem.py:254
msgid "Invalid directory specified in filesystem configuration"
msgstr ""

#: glance/store/filesystem.py:266
#, python-format
msgid "Image file %s not found"
msgstr "Image file %s not found"

#: glance/store/filesystem.py:281
#, python-format
msgid ""
"The JSON in the metadata file %(file)s could not be used: %(error)s  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:288
#, python-format
msgid ""
"The path for the metadata file %(file)s could not be opened: %(error)s  "
"An empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:295
#, python-format
msgid ""
"An error occurred processing the storage systems meta data file: %s.  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:349
#, python-format
msgid "You cannot delete file %s"
msgstr "You cannot delete file %s"

#: glance/store/filesystem.py:351
#, python-format
msgid "Image file %s does not exist"
msgstr "Image file %s does not exist"

#: glance/store/filesystem.py:396
#, python-format
msgid ""
"There is no enough disk space left on the image storage media. "
"requested=%s"
msgstr ""

#: glance/store/filesystem.py:427
#, python-format
msgid "Image file %s already exists!"
msgstr "Image file %s already exists!"

#: glance/store/filesystem.py:465
#, python-format
msgid "Unable to remove partial image data for image %(id)s: %(error)s"
msgstr ""

#: glance/store/gridfs.py:97
msgid "Missing dependencies: pymongo"
msgstr ""

#: glance/store/gridfs.py:113 glance/store/swift.py:425
#: glance/store/vmware_datastore.py:301
#, python-format
msgid "Could not find %(param)s in configuration options."
msgstr "Could not find %(param)s in configuration options."

#: glance/store/gridfs.py:180
#, python-format
msgid "GridFS already has an image at location %s"
msgstr ""

#: glance/store/http.py:82
msgid "Credentials are not well-formatted."
msgstr ""

#: glance/store/http.py:88
msgid "No address specified in HTTP URL"
msgstr "No address specified in HTTP URL"

#: glance/store/http.py:150
msgid "The HTTP URL is invalid."
msgstr ""

#: glance/store/http.py:174
msgid "HTTP datastore could not find image at URI."
msgstr ""

#: glance/store/http.py:177
#, python-format
msgid "HTTP URL returned a %s status code."
msgstr "HTTP URL returned a %s status code."

#: glance/store/http.py:184
#, python-format
msgid "The HTTP URL attempted to redirect with an invalid %s status code."
msgstr ""

#: glance/store/rbd.py:56
msgid ""
"RADOS images will be chunked into objects of this size (in megabytes). "
"For best performance, this should be a power of two."
msgstr ""

#: glance/store/rbd.py:60
msgid "RADOS pool in which images are stored."
msgstr "RADOS pool in which images are stored."

#: glance/store/rbd.py:62
msgid ""
"RADOS user to authenticate as (only applicable if using Cephx. If <None>,"
" a default will be chosen based on the client. section in "
"rbd_store_ceph_conf)."
msgstr ""

#: glance/store/rbd.py:66
msgid ""
"Ceph configuration file path. If <None>, librados will locate the default"
" config. If using cephx authentication, this file should include a "
"reference to the right keyring in a client.<USER> section."
msgstr ""

#: glance/store/rbd.py:112
msgid "URI must start with rbd://"
msgstr "URI must start with rbd://"

#: glance/store/rbd.py:120
msgid "URI contains non-ascii characters"
msgstr "URI contains non-ascii characters"

#: glance/store/rbd.py:132
msgid "URI must have exactly 1 or 4 components"
msgstr "URI must have exactly 1 or 4 components"

#: glance/store/rbd.py:137
msgid "URI cannot contain empty components"
msgstr "URI cannot contain empty components"

#: glance/store/rbd.py:172 glance/store/rbd.py:298
#, python-format
msgid "RBD image %s does not exist"
msgstr "RBD image %s does not exist"

#: glance/store/rbd.py:200 glance/store/sheepdog.py:199
#: glance/store/sheepdog.py:216
#, python-format
msgid "Error in store configuration: %s"
msgstr "Error in store configuration: %s"

#: glance/store/rbd.py:334
msgid ""
"since image size is zero we will be doing resize-before-write for each "
"chunk which will be considerably slower than normal"
msgstr ""

#: glance/store/rbd.py:343
#, python-format
msgid "RBD image %s already exists"
msgstr "RBD image %s already exists"

#: glance/store/s3.py:50
msgid "The host where the S3 server is listening."
msgstr "The host where the S3 server is listening."

#: glance/store/s3.py:52
msgid "The S3 query token access key."
msgstr "The S3 query token access key."

#: glance/store/s3.py:54
msgid "The S3 query token secret key."
msgstr "The S3 query token secret key."

#: glance/store/s3.py:56
msgid "The S3 bucket to be used to store the Glance data."
msgstr "The S3 bucket to be used to store the Glance data."

#: glance/store/s3.py:58
msgid ""
"The local directory where uploads will be staged before they are "
"transferred into S3."
msgstr ""

#: glance/store/s3.py:61
msgid ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."
msgstr ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."

#: glance/store/s3.py:65
msgid ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."
msgstr ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."

#: glance/store/s3.py:69
msgid ""
"What size, in MB, should S3 start chunking image files and do a multipart"
" upload in S3."
msgstr ""

#: glance/store/s3.py:73
msgid ""
"What multipart upload part size, in MB, should S3 use when uploading "
"parts. The size must be greater than or equal to 5M."
msgstr ""

#: glance/store/s3.py:77
msgid "The number of thread pools to perform a multipart upload in S3."
msgstr ""

#: glance/store/s3.py:198
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"
msgstr ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"

#: glance/store/s3.py:232
msgid "Badly formed S3 credentials"
msgstr ""

#: glance/store/s3.py:245
msgid "Badly formed S3 URI. Missing s3 service URL."
msgstr "Badly formed S3 URI. Missing s3 service URL."

#: glance/store/s3.py:248
msgid "Badly formed S3 URI"
msgstr ""

#: glance/store/s3.py:338
#, python-format
msgid ""
"s3_store_large_object_chunk_size must be at least %(_s3_ck_min)d MB. You "
"configured it as %(_s3_ck_size)d MB"
msgstr ""

#: glance/store/s3.py:348
#, python-format
msgid "s3_store_thread_pools must be a positive integer. %s"
msgstr ""

#: glance/store/s3.py:472
#, python-format
msgid "S3 already has an image at location %s"
msgstr "S3 already has an image at location %s"

#: glance/store/s3.py:597
#, python-format
msgid "Failed to add image object to S3. key=%(obj_name)s"
msgstr ""

#: glance/store/s3.py:685
#, python-format
msgid ""
"Failed to add bucket to S3.\n"
"Got error from S3: %s"
msgstr ""

#: glance/store/s3.py:690
#, python-format
msgid ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."
msgstr ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."

#: glance/store/sheepdog.py:43
msgid ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."
msgstr ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."

#: glance/store/sheepdog.py:47
msgid "Port of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:49
msgid "IP address of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:150
#, python-format
msgid "URI must start with '%s://'"
msgstr ""

#: glance/store/sheepdog.py:154
msgid "URI must contains well-formated image id"
msgstr ""

#: glance/store/sheepdog.py:206
#, python-format
msgid "Invalid address configuration of sheepdog store: %s"
msgstr ""

#: glance/store/sheepdog.py:237 glance/store/sheepdog.py:256
#: glance/store/sheepdog.py:317
#, python-format
msgid "Sheepdog image %s does not exist"
msgstr ""

#: glance/store/sheepdog.py:278
#, python-format
msgid "Sheepdog image %s already exists"
msgstr ""

#: glance/store/swift.py:55
msgid "Whether to use ServiceNET to communicate with the Swift storage servers."
msgstr "Whether to use ServiceNET to communicate with the Swift storage servers."

#: glance/store/swift.py:58
msgid ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace. (deprecated)"
msgstr ""

#: glance/store/swift.py:62
msgid ""
"If True, swiftclient won't check for a valid SSL certificate when "
"authenticating."
msgstr ""

#: glance/store/swift.py:65
msgid ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."
msgstr ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."

#: glance/store/swift.py:69
msgid ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."
msgstr ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."

#: glance/store/swift.py:74
msgid ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."
msgstr ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."

#: glance/store/swift.py:79
msgid ""
"Container within the account that the account should use for storing "
"images in Swift."
msgstr ""
"Container within the account that the account should use for storing "
"images in Swift."

#: glance/store/swift.py:83
msgid ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift."
msgstr ""

#: glance/store/swift.py:87
msgid ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."
msgstr ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."

#: glance/store/swift.py:90
msgid ""
"A boolean value that determines if we create the container if it does not"
" exist."
msgstr ""
"A boolean value that determines if we create the container if it does not"
" exist."

#: glance/store/swift.py:93
msgid ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."
msgstr ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."

#: glance/store/swift.py:97
msgid ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."
msgstr ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."

#: glance/store/swift.py:101
msgid ""
"If set to False, disables SSL layer compression of https swift requests. "
"Setting to False may improve performance for images which are already in "
"a compressed format, eg qcow2."
msgstr ""

#: glance/store/swift.py:106
msgid ""
"The number of times a Swift download will be retried before the request "
"fails."
msgstr ""

#: glance/store/swift.py:128
#, python-format
msgid "Swift exception raised %s"
msgstr ""

#: glance/store/swift.py:134
#, python-format
msgid "Stopping Swift retries after %d attempts"
msgstr ""

#: glance/store/swift.py:139
#, python-format
msgid ""
"Retrying Swift connection (%(retries)d/%(max_retries)d) with "
"range=%(start)d-%(end)d"
msgstr ""

#: glance/store/swift.py:226
msgid "Badly formed Swift URI. Credentials not found for account reference"
msgstr ""

#: glance/store/swift.py:277
msgid "Badly formed Swift URI."
msgstr "Badly formed Swift URI."

#: glance/store/swift.py:296
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/store/swift.py:387
#, python-format
msgid "Swift could not find object %s."
msgstr ""

#: glance/store/swift.py:438
#, python-format
msgid "Failed to delete orphaned chunk %(container)s/%(chunk)s"
msgstr ""

#: glance/store/swift.py:499
msgid "Error during chunked upload to backend, deleting stale chunks"
msgstr ""

#: glance/store/swift.py:562
msgid "Swift already has an image at this location"
msgstr "Swift already has an image at this location"

#: glance/store/swift.py:564
#, python-format
msgid ""
"Failed to add object to Swift.\n"
"Got error from Swift: %s"
msgstr ""

#: glance/store/swift.py:605 glance/store/swift.py:790
msgid "Swift could not find image at URI."
msgstr "Swift could not find image at URI."

#: glance/store/swift.py:629
#, python-format
msgid ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"

#: glance/store/swift.py:633
#, python-format
msgid ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."
msgstr ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."

#: glance/store/swift.py:663
msgid "A value for swift_store_auth_address is required."
msgstr ""

#: glance/store/swift.py:676
msgid "A value for swift_store_ref_params is required."
msgstr ""

#: glance/store/swift.py:693
msgid "Location credentials are invalid"
msgstr ""

#: glance/store/swift.py:698
msgid "Location is missing user:password information."
msgstr "Location is missing user:password information."

#: glance/store/swift.py:710
#, python-format
msgid "Badly formed tenant:user '%(user)s' in Swift URI"
msgstr "Badly formed tenant:user '%(user)s' in Swift URI"

#: glance/store/swift.py:737
msgid "Multi-tenant Swift storage requires a context."
msgstr "Multi-tenant Swift storage requires a context."

#: glance/store/swift.py:741
msgid "Multi-tenant Swift storage requires a service catalog."
msgstr "Multi-tenant Swift storage requires a service catalog."

#: glance/store/vmware_datastore.py:54
msgid ""
"ESX/ESXi or vCenter Server target system. The server value can be an IP "
"address or a DNS name."
msgstr ""

#: glance/store/vmware_datastore.py:57
msgid "Username for authenticating with VMware ESX/VC server."
msgstr ""

#: glance/store/vmware_datastore.py:60
msgid "Password for authenticating with VMware ESX/VC server."
msgstr ""

#: glance/store/vmware_datastore.py:65
msgid ""
"Inventory path to a datacenter. If the vmware_server_host specified is an"
" ESX/ESXi, the vmware_datacenter_path is optional. If specified, it "
"should be \"ha-datacenter\"."
msgstr ""

#: glance/store/vmware_datastore.py:70
msgid "Datastore associated with the datacenter."
msgstr ""

#: glance/store/vmware_datastore.py:73
msgid ""
"Number of times VMware ESX/VC server API must be retried upon connection "
"related issues."
msgstr ""

#: glance/store/vmware_datastore.py:77
msgid ""
"The interval used for polling remote tasks invoked on VMware ESX/VC "
"server."
msgstr ""

#: glance/store/vmware_datastore.py:81
msgid ""
"The name of the directory where the glance images will be stored in the "
"VMware datastore."
msgstr ""

#: glance/store/vmware_datastore.py:85
msgid "Allow to perform insecure SSL requests to ESX/VC."
msgstr ""

#: glance/store/vmware_datastore.py:216
#, python-format
msgid "URI must start with %s://"
msgstr ""

#: glance/store/vmware_datastore.py:231
msgid "Badly formed VMware datastore URI"
msgstr ""

#: glance/store/vmware_datastore.py:246
msgid "vmware_api_retry_count should be greater than zero"
msgstr ""

#: glance/store/vmware_datastore.py:251
msgid "vmware_task_poll_interval should be greater than zero"
msgstr ""

#: glance/store/vmware_datastore.py:281
#, python-format
msgid "Could not find datastore %(ds_name)s in datacenter %(dc_path)s"
msgstr ""

#: glance/store/vmware_datastore.py:370
#, python-format
msgid "Image file %(image_id)s already exists!"
msgstr ""

#: glance/store/vmware_datastore.py:469
#, python-format
msgid "HTTP request returned a %(status)s status code."
msgstr ""

#: glance/store/vmware_datastore.py:476
#, python-format
msgid ""
"The HTTP URL %(path)s attempted to redirect with an invalid %(status)s "
"status code."
msgstr ""

#: glance/tests/unit/test_migrations.py:929
#, python-format
msgid "location: %s data lost"
msgstr "location: %s data lost"

